//
//  IconCatalog.swift
//  Tenra
//
//  The SF Symbols the icon picker offers, grouped, and the search over them. The
//  data lives in IconCatalog+Data.swift, generated by
//  scripts/generate_icon_catalog.py from the SF Symbols metadata (only symbols
//  available on iOS 26.0).
//
//  Search runs over every language at once, so a Russian user typing "coffee" and
//  an English user typing "кофе" both find the cups:
//   1. concepts: finance-oriented synonyms in the app's 11 languages;
//   2. the picker's own group titles, localized by the caller;
//   3. Apple's English keywords and the symbol names themselves.
//  Pure and `nonisolated`; the index is built once, on first search.
//

import Foundation

nonisolated struct IconCatalogGroup: Sendable {
    let titleKey: String
    let symbols: [String]
}

nonisolated struct IconCatalogConcept: Sendable {
    let terms: [String]
    let symbols: [String]
}

nonisolated struct IconCatalogKeywords: Sendable {
    let symbol: String
    let words: [String]
}

nonisolated enum IconCatalog {

    /// Every grouped symbol once, in group order.
    static let allSymbols: [String] = groups.flatMap(\.symbols)

    /// Symbols matching `query`, best matches first, then catalog order.
    /// `groupTitles` are the localized titles of `groups`, in the same order, so a
    /// group name ("Транспорт") finds the whole group.
    static func search(_ query: String, groupTitles: [String] = []) -> [String] {
        let whole = normalize(query)
        guard !whole.isEmpty else { return [] }
        let words = whole.split(separator: " ").map(String.init)

        var scores: [String: Int] = [:]
        func add(_ symbols: [String], _ score: Int) {
            for symbol in symbols where score > scores[symbol, default: 0] {
                scores[symbol] = score
            }
        }
        for (queryIndex, part) in ([whole] + (words.count > 1 ? words : [])).enumerated() {
            // A single word of a multi-word query counts a little less than the whole.
            let penalty = queryIndex == 0 ? 0 : 5
            for concept in index.concepts {
                let best = concept.terms.map { termScore($0, part) }.max() ?? 0
                if best > 0 { add(concept.symbols, best - penalty) }
            }
            if part.count >= 3 {
                for (title, symbols) in zip(groupTitles.map(normalize), groups.map(\.symbols))
                where title.contains(part) {
                    add(symbols, 50 - penalty)
                }
            }
            for entry in index.symbols {
                if entry.words.contains(where: { $0.hasPrefix(part) }) {
                    add([entry.symbol], 40 - penalty)
                } else if part.count >= 3, entry.symbol.contains(part) {
                    add([entry.symbol], 20 - penalty)
                }
            }
        }

        let order = Dictionary(allSymbols.enumerated().map { ($1, $0) }, uniquingKeysWith: { first, _ in first })
        return scores.keys.sorted { lhs, rhs in
            let left = scores[lhs, default: 0], right = scores[rhs, default: 0]
            if left != right { return left > right }
            return order[lhs, default: .max] < order[rhs, default: .max]
        }
    }

    // MARK: - Matching

    /// Exact term 100, the query starting a term 80 (typing "маши" finds "машина"),
    /// an inflected form of the term 70 ("машины", "coffees"), the query starting a
    /// later word of a multi-word term 60.
    private static func termScore(_ term: String, _ query: String) -> Int {
        if term == query { return 100 }
        if term.hasPrefix(query), query.count >= minimumPrefix(query) { return 80 }
        if query.count >= 4, term.count >= 4 {
            let stem = term.prefix(max(4, term.count - 2))
            if query.hasPrefix(stem) { return 70 }
        }
        if query.count >= 3, term.split(separator: " ").dropFirst().contains(where: { $0.hasPrefix(query) }) {
            return 60
        }
        return 0
    }

    /// One CJK character already carries a word ("犬"); a Latin or Cyrillic letter
    /// does not.
    private static func minimumPrefix(_ query: String) -> Int {
        query.unicodeScalars.contains { $0.value >= 0x3040 } ? 1 : 2
    }

    /// Lowercased, accents and "ё"/"й" folded, punctuation (apostrophes, dots,
    /// hyphens) turned into spaces, spaces collapsed.
    static func normalize(_ text: String) -> String {
        let folded = text.folding(options: [.caseInsensitive, .diacriticInsensitive, .widthInsensitive], locale: nil)
        var scalars = String.UnicodeScalarView()
        for scalar in folded.unicodeScalars {
            scalars.append(CharacterSet.alphanumerics.contains(scalar) ? scalar : " ")
        }
        return String(scalars).split(separator: " ").joined(separator: " ")
    }

    // MARK: - Index

    private struct Index {
        struct Concept {
            let terms: [String]
            let symbols: [String]
        }
        struct Symbol {
            let symbol: String
            /// Apple keywords plus the name's own parts ("fork.knife" → fork, knife).
            let words: [String]
        }
        let concepts: [Concept]
        let symbols: [Symbol]
    }

    private static let index: Index = {
        let keywords = Dictionary(appleKeywords.map { ($0.symbol, $0.words) }, uniquingKeysWith: { first, _ in first })
        return Index(
            concepts: concepts.map { Index.Concept(terms: $0.terms.map(normalize), symbols: $0.symbols) },
            symbols: allSymbols.map { symbol in
                let nameParts = symbol.split(separator: ".").map(String.init).filter { $0 != "fill" }
                return Index.Symbol(symbol: symbol,
                                    words: (keywords[symbol, default: []] + nameParts).map(normalize))
            }
        )
    }()
}
