//
//  IconCatalog+Data.swift
//  Tenra
//
//  GENERATED by scripts/generate_icon_catalog.py. Do not edit by hand: change the
//  script and run it again. Every symbol is available on iOS 26.0.
//

import Foundation

nonisolated extension IconCatalog {

    static let frequentlyUsed: [String] = [
        "banknote.fill", "cart.fill", "car.fill", "bag.fill", "fork.knife", "house.fill", "briefcase.fill", "heart.fill", "airplane", "gift.fill", "creditcard.fill", "tv.fill", "book.fill", "star.fill", "bolt.fill", "flame.fill"
    ]

    static let groups: [IconCatalogGroup] = [
        IconCatalogGroup(titleKey: "iconPicker.foodAndDrinks", symbols: [
            "fork.knife", "takeoutbag.and.cup.and.straw.fill", "cup.and.saucer.fill", "cup.and.heat.waves.fill", "mug.fill", "wineglass.fill",
            "waterbottle.fill", "birthday.cake.fill", "carrot.fill", "fish.fill", "frying.pan.fill", "popcorn.fill",
            "laurel.leading", "spoon.serving", "menucard.fill",
        ]),
        IconCatalogGroup(titleKey: "iconPicker.transport", symbols: [
            "car.fill", "car.2.fill", "car.side.fill", "car.rear.fill", "suv.side.fill", "convertible.side.fill",
            "bus.fill", "bus.doubledecker.fill", "tram.fill", "tram.fill.tunnel", "lightrail.fill", "train.side.front.car",
            "cablecar.fill", "airplane", "airplane.departure", "airplane.arrival", "ferry.fill", "sailboat.fill",
            "bicycle", "scooter", "moped.fill", "motorcycle.fill", "fuelpump.fill", "ev.charger.fill",
            "bolt.car.fill", "parkingsign", "steeringwheel", "road.lanes", "tire", "box.truck.fill",
            "truck.box.fill", "location.fill", "map.fill", "signpost.right.fill", "figure.walk", "airplane.ticket.fill",
            "airplaneseat", "car.ferry.fill", "tram.card.fill", "licenseplate.fill", "key.car.radiowaves.forward.fill", "helmet.fill",
            "oilcan.fill", "gearshift.layout.sixspeed",
        ]),
        IconCatalogGroup(titleKey: "iconPicker.shopping", symbols: [
            "bag.fill", "cart.fill", "basket.fill", "handbag.fill", "storefront.fill", "tshirt.fill",
            "hanger", "shoe.fill", "shoe.2.fill", "sunglasses.fill", "crown.fill", "tag.fill",
            "giftcard.fill", "purchased", "barcode", "qrcode", "backpack.fill", "receipt.fill",
            "hat.cap.fill", "hat.widebrim.fill", "jacket.fill", "coat.fill",
        ]),
        IconCatalogGroup(titleKey: "iconPicker.homeAndUtilities", symbols: [
            "house.fill", "house.lodge.fill", "building.fill", "building.2.fill", "key.fill", "door.left.hand.open",
            "sofa.fill", "chair.fill", "chair.lounge.fill", "bed.double.fill", "lamp.desk.fill", "lamp.floor.fill",
            "lamp.table.fill", "lamp.ceiling.fill", "lightbulb.fill", "lightbulb.led.fill", "fan.fill", "air.conditioner.horizontal.fill",
            "heater.vertical.fill", "fireplace.fill", "bolt.fill", "powerplug.fill", "powercord.fill", "drop.fill",
            "flame.fill", "spigot.fill", "shower.fill", "bathtub.fill", "toilet.fill", "sink.fill",
            "washer.fill", "dryer.fill", "dishwasher.fill", "refrigerator.fill", "oven.fill", "stove.fill",
            "microwave.fill", "cooktop.fill", "trash.fill", "window.vertical.closed", "blinds.vertical.closed", "curtains.closed",
            "wifi.router.fill", "sprinkler.and.droplets.fill", "chandelier.fill", "table.furniture.fill", "cabinet.fill", "stairs",
            "robotic.vacuum.fill", "humidifier.fill", "air.purifier.fill", "fan.ceiling.fill", "fan.desk.fill", "lightswitch.on.fill",
            "poweroutlet.type.f.fill", "video.doorbell.fill", "window.casement", "shower.handheld.fill", "air.conditioner.vertical.fill", "dehumidifier.fill",
            "sprinkler.fill", "fire.extinguisher.fill",
        ]),
        IconCatalogGroup(titleKey: "iconPicker.health", symbols: [
            "cross.case.fill", "cross.fill", "pills.fill", "syringe.fill", "bandage.fill", "stethoscope",
            "waveform.path.ecg", "heart.text.clipboard.fill", "cross.vial.fill", "medical.thermometer.fill", "ivfluid.bag.fill", "lungs.fill",
            "brain.fill", "brain.head.profile.fill", "ear.fill", "eye.fill", "eyeglasses", "mouth.fill",
            "allergens.fill", "facemask.fill", "microbe.fill", "staroflife.fill", "testtube.2", "flask.fill",
            "figure.mind.and.body", "pill.fill", "blood.pressure.cuff.fill", "inhaler.fill", "apple.meditate", "bolt.heart.fill",
            "staroflife.shield.fill", "thermometer.medium",
        ]),
        IconCatalogGroup(titleKey: "iconPicker.group.beauty", symbols: [
            "comb.fill", "scissors", "sparkles", "hands.and.sparkles.fill", "face.smiling.fill", "mustache.fill",
            "eyebrow", "wand.and.stars", "eyedropper.halffull",
        ]),
        IconCatalogGroup(titleKey: "iconPicker.group.family", symbols: [
            "figure.2.and.child.holdinghands", "figure.and.child.holdinghands", "figure.child", "stroller.fill", "teddybear.fill", "person.fill",
            "person.2.fill", "person.3.fill", "figure.2.arms.open", "hands.clap.fill", "hand.thumbsup.fill", "heart.fill",
            "suit.heart.fill", "figure.2",
        ]),
        IconCatalogGroup(titleKey: "iconPicker.group.pets", symbols: [
            "pawprint.fill", "dog.fill", "cat.fill", "bird.fill", "hare.fill", "tortoise.fill",
            "lizard.fill", "ant.fill", "ladybug.fill", "pet.carrier.fill", "service.dog.fill",
        ]),
        IconCatalogGroup(titleKey: "iconPicker.group.educationWork", symbols: [
            "graduationcap.fill", "book.fill", "book.closed.fill", "books.vertical.fill", "text.book.closed.fill", "pencil",
            "pencil.and.ruler.fill", "ruler.fill", "highlighter", "studentdesk", "magazine.fill", "newspaper.fill",
            "briefcase.fill", "doc.fill", "doc.text.fill", "folder.fill", "tray.fill", "archivebox.fill",
            "paperclip", "list.clipboard.fill", "pencil.and.list.clipboard", "note.text", "signature", "compass.drawing",
            "globe.desk.fill", "atom", "function", "eraser.fill", "scroll.fill", "clipboard.fill",
            "text.document.fill", "megaphone.fill", "lanyardcard.fill", "pencil.tip",
        ]),
        IconCatalogGroup(titleKey: "iconPicker.moneyAndFinance", symbols: [
            "banknote.fill", "dollarsign", "eurosign", "rublesign", "tengesign", "sterlingsign",
            "yensign", "chineseyuanrenminbisign", "turkishlirasign", "wonsign", "indianrupeesign", "bitcoinsign",
            "creditcard.fill", "wallet.pass.fill", "wallet.bifold.fill", "building.columns.fill", "chart.bar.fill", "chart.line.uptrend.xyaxis",
            "chart.pie.fill", "percent", "shield.fill", "checkmark.shield.fill", "lock.shield.fill", "umbrella.fill",
            "lock.fill", "hryvniasign", "brazilianrealsign", "polishzlotysign", "larisign", "manatsign",
            "dongsign", "bahtsign", "pesosign", "francsign", "australiandollarsign", "swedishkronasign",
            "norwegiankronesign", "danishkronesign", "shekelsign", "singaporedollarsign", "malaysianringgitsign", "nairasign",
            "centsign", "creditcard.rewards.fill", "chart.xyaxis.line", "arrow.left.arrow.right", "arrow.triangle.2.circlepath",
        ]),
        IconCatalogGroup(titleKey: "iconPicker.entertainment", symbols: [
            "film.fill", "film.stack.fill", "movieclapper.fill", "tv.fill", "gamecontroller.fill", "puzzlepiece.fill",
            "dice.fill", "die.face.5.fill", "music.note", "music.note.list", "music.mic", "guitars.fill",
            "pianokeys", "theatermasks.fill", "ticket.fill", "party.popper.fill", "paintpalette.fill", "paintbrush.fill",
            "camera.fill", "photo.fill", "figure.dance", "figure.socialdance", "play.tv.fill", "microphone.fill",
            "photo.artframe", "arcade.stick", "metronome.fill",
        ]),
        IconCatalogGroup(titleKey: "iconPicker.group.travel", symbols: [
            "suitcase.fill", "suitcase.rolling.fill", "suitcase.cart.fill", "beach.umbrella.fill", "tent.fill", "tent.2.fill",
            "mountain.2.fill", "binoculars.fill", "globe.fill", "globe.europe.africa.fill", "globe.americas.fill", "globe.asia.australia.fill",
            "mappin", "flag.checkered", "figure.hiking", "figure.walk.suitcase.rolling", "globe.central.south.asia.fill", "lifepreserver.fill",
            "sun.horizon.fill",
        ]),
        IconCatalogGroup(titleKey: "iconPicker.group.sports", symbols: [
            "dumbbell.fill", "sportscourt.fill", "stopwatch.fill", "trophy.fill", "medal.fill", "soccerball",
            "basketball.fill", "football.fill", "tennis.racket", "tennisball.fill", "baseball.fill", "volleyball.fill",
            "hockey.puck.fill", "skateboard.fill", "skis.fill", "snowboard.fill", "surfboard.fill", "oar.2.crossed",
            "figure.run", "figure.run.treadmill", "figure.strengthtraining.traditional", "figure.strengthtraining.functional", "figure.cross.training", "figure.core.training",
            "figure.highintensity.intervaltraining", "figure.mixed.cardio", "figure.elliptical", "figure.stair.stepper", "figure.jumprope", "figure.yoga",
            "figure.pilates", "figure.flexibility", "figure.cooldown", "figure.pool.swim", "figure.open.water.swim", "figure.water.fitness",
            "figure.outdoor.cycle", "figure.indoor.cycle", "figure.soccer", "figure.basketball", "figure.volleyball", "figure.tennis",
            "figure.table.tennis", "figure.badminton", "figure.hockey", "figure.ice.hockey", "figure.ice.skating", "figure.skating",
            "figure.skiing.downhill", "figure.skiing.crosscountry", "figure.snowboarding", "figure.skateboarding", "figure.surfing", "figure.sailing",
            "figure.rower", "figure.climbing", "figure.boxing", "figure.kickboxing", "figure.martial.arts", "figure.wrestling",
            "figure.fencing", "figure.gymnastics", "figure.golf", "figure.bowling", "figure.archery", "figure.equestrian.sports",
            "figure.track.and.field", "figure.fishing", "figure.hunting", "figure.american.football", "figure.baseball", "figure.handball",
            "figure.rugby", "figure.taichi", "rugbyball.fill", "cricket.ball.fill", "duffle.bag.fill", "flag.pattern.checkered",
            "figure.squash", "figure.indoor.rowing", "figure.barre", "figure.step.training", "figure.walk.treadmill", "figure.curling",
        ]),
        IconCatalogGroup(titleKey: "iconPicker.group.tech", symbols: [
            "iphone", "ipad", "laptopcomputer", "desktopcomputer", "display", "applewatch",
            "airpods", "airpodspro", "airpodsmax", "earbuds", "headphones", "homepod.fill",
            "appletv.fill", "visionpro.fill", "macmini.fill", "keyboard.fill", "computermouse.fill", "printer.fill",
            "scanner.fill", "externaldrive.fill", "cpu.fill", "memorychip.fill", "flipphone", "candybarphone",
            "phone.fill", "message.fill", "bubble.left.fill", "envelope.fill", "antenna.radiowaves.left.and.right", "wifi",
            "network", "icloud.fill", "simcard.fill", "battery.100", "cable.connector", "hifispeaker.fill",
            "radio.fill", "macbook", "pc", "airtag.fill", "applepencil", "headset",
            "server.rack", "sdcard.fill", "internaldrive.fill", "personalhotspot", "esim.fill", "faxmachine.fill",
            "4k.tv.fill", "video.fill", "envelope.open.fill", "translate", "waveform",
        ]),
        IconCatalogGroup(titleKey: "iconPicker.group.services", symbols: [
            "wrench.adjustable.fill", "wrench.and.screwdriver.fill", "hammer.fill", "screwdriver.fill", "paintbrush.pointed.fill", "level.fill",
            "shippingbox.fill", "paperplane.fill", "scalemass.fill", "gearshape.fill", "gearshape.2.fill", "bell.fill",
            "checkmark.seal.fill", "exclamationmark.triangle.fill", "hand.raised.fill", "magnifyingglass", "flashlight.on.fill", "key.card.fill",
        ]),
        IconCatalogGroup(titleKey: "iconPicker.group.celebrations", symbols: [
            "gift.fill", "balloon.fill", "balloon.2.fill", "fireworks", "star.fill", "rosette",
            "greetingcard.fill", "medal.star.fill",
        ]),
        IconCatalogGroup(titleKey: "iconPicker.group.nature", symbols: [
            "leaf.fill", "tree.fill", "camera.macro", "sun.max.fill", "moon.fill", "cloud.fill",
            "cloud.rain.fill", "cloud.snow.fill", "cloud.bolt.fill", "snowflake", "wind", "rainbow",
            "sunrise.fill", "sunset.fill", "thermometer.sun.fill", "humidity.fill", "tornado", "water.waves",
            "cloud.sun.fill", "cloud.moon.fill", "moon.stars.fill", "cloud.drizzle.fill", "cloud.fog.fill", "cloud.heavyrain.fill",
            "sun.haze.fill", "hurricane", "tropicalstorm", "smoke.fill",
        ]),
        IconCatalogGroup(titleKey: "iconPicker.group.symbols", symbols: [
            "bookmark.fill", "flag.fill", "pin.fill", "infinity", "hourglass", "timer",
            "alarm.fill", "clock.fill", "calendar", "seal.fill", "diamond.fill", "hexagon.fill",
            "octagon.fill", "triangle.fill", "rhombus.fill", "capsule.fill", "suit.spade.fill", "suit.club.fill",
            "suit.diamond.fill", "link", "at", "number", "questionmark", "exclamationmark",
        ]),
    ]

    static let concepts: [IconCatalogConcept] = [
        IconCatalogConcept(
            terms: ["food", "meal", "eat", "dinner", "lunch", "breakfast", "еда", "питание", "обед", "ужин", "завтрак", "їжа", "харчування", "обід", "вечеря", "сніданок", "essen", "mahlzeit", "mittagessen", "abendessen", "frühstück", "comida", "almuerzo", "cena", "desayuno", "nourriture", "repas", "déjeuner", "dîner", "petit-déjeuner", "cibo", "pasto", "pranzo", "colazione", "refeição", "almoço", "jantar", "café da manhã", "yemek", "gıda", "öğle yemeği", "akşam yemeği", "kahvaltı", "食べ物", "食事", "昼食", "夕食", "朝食", "ごはん", "음식", "식사", "점심", "저녁", "아침"],
            symbols: ["fork.knife", "takeoutbag.and.cup.and.straw.fill", "carrot.fill", "fish.fill", "frying.pan.fill", "birthday.cake.fill"]
        ),
        IconCatalogConcept(
            terms: ["restaurant", "restaurants", "dining", "ресторан", "рестораны", "ресторани", "restaurante", "ristorante", "restoran", "lokanta", "レストラン", "外食", "레스토랑", "식당", "외식"],
            symbols: ["fork.knife"]
        ),
        IconCatalogConcept(
            terms: ["coffee", "cafe", "coffee shop", "кофе", "кафе", "кофейня", "кава", "кав'ярня", "kaffee", "café", "cafetería", "caffè", "bar", "cafeteria", "kahve", "kafe", "コーヒー", "カフェ", "喫茶", "커피", "카페"],
            symbols: ["cup.and.saucer.fill", "mug.fill", "cup.and.heat.waves.fill"]
        ),
        IconCatalogConcept(
            terms: ["tea", "чай", "tee", "té", "thé", "tè", "chá", "çay", "お茶", "紅茶", "차"],
            symbols: ["cup.and.saucer.fill", "mug.fill"]
        ),
        IconCatalogConcept(
            terms: ["fast food", "takeaway", "takeout", "food delivery", "фастфуд", "еда на вынос", "доставка еды", "їжа на винос", "доставка їжі", "fastfood", "imbiss", "essen zum mitnehmen", "lieferdienst", "comida rápida", "para llevar", "comida a domicilio", "fast-food", "à emporter", "livraison de repas", "da asporto", "cibo a domicilio", "para viagem", "delivery", "paket servis", "yemek siparişi", "ファストフード", "テイクアウト", "出前", "패스트푸드", "포장", "배달음식"],
            symbols: ["takeoutbag.and.cup.and.straw.fill", "shippingbox.fill"]
        ),
        IconCatalogConcept(
            terms: ["groceries", "grocery", "supermarket", "продукты", "супермаркет", "магазин", "продукти", "lebensmittel", "supermarkt", "einkauf", "supermercado", "comestibles", "alimentos", "courses", "supermarché", "épicerie", "spesa", "supermercato", "alimentari", "mercado", "mantimentos", "market", "süpermarket", "bakkal", "食料品", "スーパー", "식료품", "마트", "장보기"],
            symbols: ["cart.fill", "basket.fill", "carrot.fill", "bag.fill", "storefront.fill"]
        ),
        IconCatalogConcept(
            terms: ["vegetables", "fruit", "healthy food", "овощи", "фрукты", "овочі", "фрукти", "gemüse", "obst", "verduras", "frutas", "légumes", "fruits", "verdura", "frutta", "legumes", "sebze", "meyve", "野菜", "果物", "채소", "과일"],
            symbols: ["carrot.fill", "leaf.fill"]
        ),
        IconCatalogConcept(
            terms: ["fish", "seafood", "sushi", "рыба", "морепродукты", "суши", "риба", "морепродукти", "суші", "fisch", "meeresfrüchte", "pescado", "marisco", "poisson", "fruits de mer", "pesce", "frutti di mare", "peixe", "frutos do mar", "balık", "deniz ürünleri", "suşi", "魚", "寿司", "海鮮", "생선", "해산물", "초밥"],
            symbols: ["fish.fill"]
        ),
        IconCatalogConcept(
            terms: ["dessert", "sweets", "cake", "bakery", "pastry", "сладости", "десерт", "торт", "выпечка", "пекарня", "солодощі", "випічка", "süßigkeiten", "kuchen", "bäckerei", "dulces", "postre", "pastel", "panadería", "desserts", "sucreries", "gâteau", "boulangerie", "pâtisserie", "dolci", "torta", "panetteria", "pasticceria", "doces", "sobremesa", "bolo", "padaria", "tatlı", "pasta", "fırın", "スイーツ", "デザート", "ケーキ", "パン屋", "디저트", "과자", "케이크", "빵집"],
            symbols: ["birthday.cake.fill"]
        ),
        IconCatalogConcept(
            terms: ["alcohol", "wine", "beer", "bar", "drinks", "pub", "алкоголь", "вино", "пиво", "бар", "напитки", "напої", "alkohol", "wein", "bier", "getränke", "kneipe", "vino", "cerveza", "bebidas", "alcool", "vin", "bière", "boissons", "alcol", "birra", "bevande", "álcool", "vinho", "cerveja", "alkol", "şarap", "bira", "içecek", "お酒", "ワイン", "ビール", "バー", "飲み物", "술", "와인", "맥주", "바", "음료"],
            symbols: ["wineglass.fill", "mug.fill"]
        ),
        IconCatalogConcept(
            terms: ["water", "вода", "wasser", "agua", "eau", "acqua", "água", "su", "水", "물"],
            symbols: ["waterbottle.fill", "drop.fill"]
        ),
        IconCatalogConcept(
            terms: ["car", "auto", "vehicle", "driving", "машина", "авто", "автомобиль", "автомобіль", "wagen", "fahrzeug", "coche", "carro", "vehículo", "voiture", "véhicule", "macchina", "veicolo", "automóvel", "veículo", "araba", "otomobil", "araç", "車", "自動車", "자동차", "차"],
            symbols: ["car.fill", "car.2.fill", "car.side.fill", "car.rear.fill", "suv.side.fill", "convertible.side.fill", "steeringwheel", "licenseplate.fill", "key.car.radiowaves.forward.fill"]
        ),
        IconCatalogConcept(
            terms: ["taxi", "cab", "uber", "ride", "такси", "таксі", "táxi", "taksi", "タクシー", "택시"],
            symbols: ["car.fill", "car.side.fill"]
        ),
        IconCatalogConcept(
            terms: ["fuel", "gas", "petrol", "gas station", "charging", "бензин", "топливо", "заправка", "азс", "зарядка", "пальне", "benzin", "tanken", "tankstelle", "kraftstoff", "laden", "gasolina", "combustible", "gasolinera", "carga", "essence", "carburant", "station-service", "recharge", "benzina", "carburante", "distributore", "ricarica", "combustível", "posto", "recarga", "yakıt", "akaryakıt", "şarj", "ガソリン", "燃料", "給油", "充電", "주유", "휘발유", "연료", "충전"],
            symbols: ["fuelpump.fill", "ev.charger.fill", "bolt.car.fill"]
        ),
        IconCatalogConcept(
            terms: ["parking", "парковка", "стоянка", "паркування", "parken", "parkplatz", "aparcamiento", "estacionamiento", "stationnement", "parcheggio", "estacionamento", "otopark", "park", "駐車場", "パーキング", "주차"],
            symbols: ["parkingsign", "car.fill"]
        ),
        IconCatalogConcept(
            terms: ["public transport", "transit", "bus", "metro", "subway", "tram", "train", "транспорт", "общественный транспорт", "автобус", "метро", "трамвай", "поезд", "электричка", "громадський транспорт", "потяг", "nahverkehr", "u-bahn", "straßenbahn", "zug", "bahn", "transporte público", "autobús", "tranvía", "tren", "transports en commun", "métro", "trasporto pubblico", "autobus", "treno", "ônibus", "metrô", "trem", "bonde", "toplu taşıma", "otobüs", "tramvay", "交通", "公共交通", "バス", "地下鉄", "電車", "路面電車", "대중교통", "버스", "지하철", "트램", "기차"],
            symbols: ["bus.fill", "bus.doubledecker.fill", "tram.fill", "tram.fill.tunnel", "lightrail.fill", "train.side.front.car", "cablecar.fill", "tram.card.fill"]
        ),
        IconCatalogConcept(
            terms: ["flight", "plane", "airplane", "airline", "airport", "самолёт", "авиабилеты", "перелёт", "авиа", "аэропорт", "літак", "авіаквитки", "переліт", "аеропорт", "flug", "flugzeug", "flughafen", "vuelo", "avión", "aeropuerto", "vol", "avion", "aéroport", "volo", "aereo", "aeroporto", "voo", "avião", "uçak", "uçuş", "havalimanı", "飛行機", "航空券", "空港", "비행기", "항공권", "공항"],
            symbols: ["airplane", "airplane.departure", "airplane.arrival", "airplane.ticket.fill", "airplaneseat"]
        ),
        IconCatalogConcept(
            terms: ["bike", "bicycle", "scooter", "motorcycle", "велосипед", "самокат", "мотоцикл", "скутер", "fahrrad", "roller", "motorrad", "bicicleta", "patinete", "moto", "vélo", "trottinette", "bici", "bicicletta", "monopattino", "bisiklet", "motosiklet", "自転車", "スクーター", "バイク", "자전거", "킥보드", "오토바이"],
            symbols: ["bicycle", "scooter", "moped.fill", "motorcycle.fill", "figure.outdoor.cycle"]
        ),
        IconCatalogConcept(
            terms: ["boat", "ferry", "ship", "лодка", "паром", "корабль", "човен", "пором", "корабель", "boot", "fähre", "schiff", "barco", "bateau", "barca", "traghetto", "nave", "balsa", "navio", "tekne", "feribot", "gemi", "船", "フェリー", "배", "페리"],
            symbols: ["ferry.fill", "sailboat.fill"]
        ),
        IconCatalogConcept(
            terms: ["car service", "car repair", "tires", "maintenance", "автосервис", "ремонт авто", "шины", "техобслуживание", "автосервіс", "шини", "werkstatt", "autoreparatur", "reifen", "wartung", "taller", "reparación", "neumáticos", "mantenimiento", "garage", "réparation", "pneus", "entretien", "officina", "riparazione", "gomme", "manutenzione", "oficina", "conserto", "manutenção", "servis", "tamir", "lastik", "bakım", "整備", "修理", "タイヤ", "정비", "수리", "타이어"],
            symbols: ["wrench.adjustable.fill", "wrench.and.screwdriver.fill", "tire", "oilcan.fill"]
        ),
        IconCatalogConcept(
            terms: ["shopping", "store", "shop", "mall", "purchase", "покупки", "шопинг", "магазин", "торговый центр", "шопінг", "einkaufen", "laden", "geschäft", "compras", "tienda", "centro comercial", "achats", "magasin", "boutique", "acquisti", "negozio", "loja", "alışveriş", "mağaza", "avm", "買い物", "ショッピング", "店", "쇼핑", "구매", "매장"],
            symbols: ["bag.fill", "cart.fill", "handbag.fill", "storefront.fill", "basket.fill", "receipt.fill"]
        ),
        IconCatalogConcept(
            terms: ["clothes", "clothing", "fashion", "shoes", "apparel", "одежда", "обувь", "мода", "одяг", "взуття", "kleidung", "schuhe", "mode", "ropa", "zapatos", "moda", "calzado", "vêtements", "chaussures", "vestiti", "abbigliamento", "scarpe", "roupas", "sapatos", "calçados", "giyim", "kıyafet", "ayakkabı", "服", "衣類", "靴", "ファッション", "옷", "의류", "신발", "패션"],
            symbols: ["tshirt.fill", "hanger", "shoe.fill", "shoe.2.fill", "handbag.fill", "sunglasses.fill", "hat.cap.fill", "hat.widebrim.fill", "jacket.fill", "coat.fill"]
        ),
        IconCatalogConcept(
            terms: ["delivery", "parcel", "package", "online shopping", "marketplace", "доставка", "посылка", "маркетплейс", "интернет-магазин", "посилка", "lieferung", "paket", "versand", "onlineshop", "envío", "paquete", "entrega", "tienda online", "livraison", "colis", "achats en ligne", "consegna", "pacco", "spedizione", "acquisti online", "pacote", "encomenda", "compras online", "kargo", "teslimat", "online alışveriş", "配送", "荷物", "宅配", "通販", "배송", "택배", "소포", "온라인 쇼핑"],
            symbols: ["shippingbox.fill", "box.truck.fill", "truck.box.fill"]
        ),
        IconCatalogConcept(
            terms: ["home", "house", "rent", "apartment", "mortgage", "дом", "квартира", "аренда", "жильё", "ипотека", "дім", "оренда", "житло", "іпотека", "zuhause", "haus", "miete", "wohnung", "hypothek", "casa", "hogar", "alquiler", "piso", "hipoteca", "maison", "logement", "loyer", "appartement", "hypothèque", "affitto", "appartamento", "mutuo", "aluguel", "apartamento", "moradia", "ev", "kira", "daire", "konut", "ipotek", "家", "住まい", "家賃", "マンション", "住宅ローン", "집", "주거", "월세", "아파트", "대출"],
            symbols: ["house.fill", "house.lodge.fill", "building.fill", "building.2.fill", "key.fill", "door.left.hand.open"]
        ),
        IconCatalogConcept(
            terms: ["furniture", "interior", "bed", "sofa", "мебель", "интерьер", "кровать", "диван", "меблі", "інтер'єр", "ліжко", "möbel", "einrichtung", "bett", "muebles", "cama", "sofá", "meubles", "mobilier", "lit", "canapé", "mobili", "arredamento", "letto", "divano", "móveis", "mobilya", "yatak", "koltuk", "家具", "インテリア", "ベッド", "ソファ", "가구", "인테리어", "침대", "소파"],
            symbols: ["sofa.fill", "chair.fill", "chair.lounge.fill", "bed.double.fill", "lamp.desk.fill", "lamp.floor.fill", "lamp.table.fill", "lamp.ceiling.fill", "table.furniture.fill", "cabinet.fill", "chandelier.fill"]
        ),
        IconCatalogConcept(
            terms: ["utilities", "bills", "electricity", "water", "gas", "heating", "коммунальные", "коммуналка", "счета", "электричество", "свет", "газ", "отопление", "жкх", "комунальні", "комуналка", "рахунки", "електрика", "світло", "опалення", "nebenkosten", "rechnungen", "strom", "heizung", "servicios", "facturas", "luz", "electricidad", "calefacción", "charges", "factures", "électricité", "gaz", "chauffage", "utenze", "bollette", "luce", "elettricità", "riscaldamento", "contas", "energia", "gás", "aquecimento", "fatura", "faturalar", "elektrik", "doğalgaz", "ısınma", "光熱費", "公共料金", "電気", "ガス", "暖房", "공과금", "관리비", "전기", "가스", "난방"],
            symbols: ["bolt.fill", "lightbulb.fill", "drop.fill", "flame.fill", "powerplug.fill", "spigot.fill", "fan.fill", "heater.vertical.fill", "air.conditioner.horizontal.fill", "lightswitch.on.fill", "poweroutlet.type.f.fill"]
        ),
        IconCatalogConcept(
            terms: ["internet", "phone", "mobile", "cellular", "wifi", "communication", "интернет", "связь", "телефон", "мобильная связь", "сотовая", "інтернет", "зв'язок", "мобільний", "telefon", "handy", "mobilfunk", "teléfono", "móvil", "celular", "téléphone", "forfait", "telefono", "cellulare", "telefone", "cep", "mobil", "インターネット", "電話", "携帯", "通信", "인터넷", "전화", "휴대폰", "통신"],
            symbols: ["wifi", "wifi.router.fill", "network", "globe.fill", "phone.fill", "iphone", "antenna.radiowaves.left.and.right", "simcard.fill", "personalhotspot", "esim.fill"]
        ),
        IconCatalogConcept(
            terms: ["appliances", "kitchen", "fridge", "washing machine", "бытовая техника", "кухня", "холодильник", "стиральная машина", "побутова техніка", "пральна машина", "haushaltsgeräte", "küche", "kühlschrank", "waschmaschine", "electrodomésticos", "cocina", "nevera", "lavadora", "électroménager", "cuisine", "frigo", "lave-linge", "elettrodomestici", "cucina", "lavatrice", "eletrodomésticos", "cozinha", "geladeira", "máquina de lavar", "beyaz eşya", "mutfak", "buzdolabı", "çamaşır makinesi", "家電", "キッチン", "冷蔵庫", "洗濯機", "가전", "주방", "냉장고", "세탁기"],
            symbols: ["refrigerator.fill", "oven.fill", "stove.fill", "microwave.fill", "cooktop.fill", "dishwasher.fill", "washer.fill", "dryer.fill", "frying.pan.fill"]
        ),
        IconCatalogConcept(
            terms: ["cleaning", "laundry", "household", "уборка", "стирка", "химчистка", "бытовая химия", "хозяйство", "прибирання", "прання", "хімчистка", "побутова хімія", "putzen", "reinigung", "wäsche", "haushalt", "limpieza", "lavandería", "hogar", "ménage", "nettoyage", "lessive", "pressing", "pulizie", "lavanderia", "casa", "limpeza", "temizlik", "çamaşır", "kuru temizleme", "掃除", "洗濯", "クリーニング", "日用品", "청소", "세탁", "세탁소", "생활용품"],
            symbols: ["washer.fill", "sparkles", "trash.fill", "shower.fill", "robotic.vacuum.fill"]
        ),
        IconCatalogConcept(
            terms: ["repair", "renovation", "tools", "construction", "ремонт", "стройка", "инструменты", "стройматериалы", "будівництво", "інструменти", "reparatur", "renovierung", "werkzeug", "baumarkt", "reparación", "reforma", "herramientas", "obra", "réparation", "travaux", "rénovation", "outils", "riparazione", "ristrutturazione", "attrezzi", "reparo", "ferramentas", "tamir", "tadilat", "alet", "inşaat", "修理", "リフォーム", "工具", "수리", "리모델링", "공구", "공사"],
            symbols: ["hammer.fill", "wrench.and.screwdriver.fill", "screwdriver.fill", "paintbrush.fill", "paintbrush.pointed.fill", "ruler.fill", "level.fill", "wrench.adjustable.fill"]
        ),
        IconCatalogConcept(
            terms: ["health", "medicine", "doctor", "hospital", "clinic", "medical", "здоровье", "медицина", "врач", "больница", "клиника", "поликлиника", "здоров'я", "лікар", "лікарня", "клініка", "gesundheit", "medizin", "arzt", "krankenhaus", "klinik", "salud", "medicina", "médico", "clínica", "santé", "médecine", "médecin", "hôpital", "clinique", "salute", "medico", "ospedale", "clinica", "saúde", "sağlık", "tıp", "doktor", "hastane", "健康", "医療", "病院", "医者", "クリニック", "건강", "의료", "병원", "의사", "클리닉"],
            symbols: ["cross.case.fill", "cross.fill", "pills.fill", "syringe.fill", "bandage.fill", "stethoscope", "waveform.path.ecg", "heart.text.clipboard.fill", "cross.vial.fill", "medical.thermometer.fill", "pill.fill", "blood.pressure.cuff.fill", "inhaler.fill"]
        ),
        IconCatalogConcept(
            terms: ["pharmacy", "drugstore", "pills", "drugs", "аптека", "лекарства", "таблетки", "ліки", "apotheke", "medikamente", "tabletten", "farmacia", "medicamentos", "pastillas", "pharmacie", "médicaments", "farmaci", "medicine", "farmácia", "remédios", "eczane", "ilaç", "薬局", "薬", "약국", "약"],
            symbols: ["pills.fill", "cross.case.fill", "syringe.fill", "cross.vial.fill", "pill.fill"]
        ),
        IconCatalogConcept(
            terms: ["dentist", "teeth", "dental", "стоматолог", "зубы", "дантист", "зуби", "zahnarzt", "zähne", "dentista", "dientes", "dentiste", "dents", "denti", "dentes", "diş", "dişçi", "diş hekimi", "歯医者", "歯科", "치과", "치아"],
            symbols: ["mouth.fill"]
        ),
        IconCatalogConcept(
            terms: ["glasses", "optics", "eyes", "vision", "очки", "оптика", "зрение", "глаза", "окуляри", "зір", "brille", "optiker", "augen", "gafas", "óptica", "ojos", "lunettes", "opticien", "yeux", "occhiali", "ottica", "occhi", "óculos", "ótica", "olhos", "gözlük", "optik", "göz", "眼鏡", "メガネ", "目", "안경", "안과", "눈"],
            symbols: ["eye.fill", "eyeglasses"]
        ),
        IconCatalogConcept(
            terms: ["insurance", "protection", "страховка", "страхование", "защита", "страхування", "захист", "versicherung", "schutz", "seguro", "protección", "assurance", "assicurazione", "protezione", "proteção", "sigorta", "koruma", "保険", "保障", "보험", "보장"],
            symbols: ["shield.fill", "checkmark.shield.fill", "umbrella.fill", "lock.shield.fill"]
        ),
        IconCatalogConcept(
            terms: ["gym", "fitness", "sport", "sports", "workout", "training", "спорт", "фитнес", "спортзал", "тренировки", "зал", "фітнес", "тренування", "fitnessstudio", "gimnasio", "deporte", "entrenamiento", "salle de sport", "entraînement", "palestra", "allenamento", "academia", "esporte", "treino", "spor", "spor salonu", "antrenman", "ジム", "スポーツ", "フィットネス", "トレーニング", "헬스", "운동", "피트니스", "스포츠"],
            symbols: ["dumbbell.fill", "figure.strengthtraining.traditional", "figure.run", "figure.yoga", "figure.pool.swim", "sportscourt.fill"]
        ),
        IconCatalogConcept(
            terms: ["yoga", "meditation", "wellness", "spa", "йога", "медитация", "спа", "релакс", "медитація", "meditación", "bienestar", "méditation", "bien-être", "meditazione", "benessere", "ioga", "meditação", "bem-estar", "meditasyon", "ヨガ", "瞑想", "スパ", "요가", "명상", "스파"],
            symbols: ["figure.yoga", "figure.mind.and.body", "figure.pilates", "figure.taichi", "leaf.fill"]
        ),
        IconCatalogConcept(
            terms: ["swimming", "pool", "плавание", "бассейн", "плавання", "басейн", "schwimmen", "schwimmbad", "natación", "piscina", "natation", "piscine", "nuoto", "natação", "yüzme", "havuz", "水泳", "プール", "수영", "수영장"],
            symbols: ["figure.pool.swim", "figure.open.water.swim", "figure.water.fitness", "water.waves"]
        ),
        IconCatalogConcept(
            terms: ["running", "jogging", "marathon", "бег", "пробежка", "марафон", "біг", "пробіжка", "laufen", "joggen", "correr", "maratón", "course", "corsa", "maratona", "corrida", "koşu", "maraton", "ランニング", "マラソン", "달리기", "러닝", "마라톤"],
            symbols: ["figure.run", "figure.run.treadmill", "figure.track.and.field", "stopwatch.fill"]
        ),
        IconCatalogConcept(
            terms: ["football", "soccer", "футбол", "fußball", "fútbol", "foot", "calcio", "futebol", "futbol", "サッカー", "축구"],
            symbols: ["soccerball", "figure.soccer"]
        ),
        IconCatalogConcept(
            terms: ["basketball", "баскетбол", "baloncesto", "basket", "pallacanestro", "basquete", "basketbol", "バスケ", "バスケットボール", "농구"],
            symbols: ["basketball.fill", "figure.basketball"]
        ),
        IconCatalogConcept(
            terms: ["tennis", "ping pong", "badminton", "теннис", "настольный теннис", "бадминтон", "теніс", "бадмінтон", "tischtennis", "tenis", "pádel", "bádminton", "ping-pong", "tênis", "pingue-pongue", "masa tenisi", "テニス", "卓球", "バドミントン", "테니스", "탁구", "배드민턴"],
            symbols: ["tennis.racket", "tennisball.fill", "figure.tennis", "figure.table.tennis", "figure.badminton"]
        ),
        IconCatalogConcept(
            terms: ["volleyball", "волейбол", "voleibol", "volley", "pallavolo", "vôlei", "voleybol", "バレーボール", "배구"],
            symbols: ["volleyball.fill", "figure.volleyball"]
        ),
        IconCatalogConcept(
            terms: ["hockey", "skating", "ice rink", "хоккей", "коньки", "каток", "хокей", "ковзани", "ковзанка", "eishockey", "schlittschuh", "eisbahn", "patinaje", "patinoire", "patin", "pattinaggio", "hóquei", "patinação", "hokey", "paten", "buz pateni", "ホッケー", "スケート", "하키", "스케이트"],
            symbols: ["hockey.puck.fill", "figure.hockey", "figure.ice.hockey", "figure.ice.skating", "figure.skating"]
        ),
        IconCatalogConcept(
            terms: ["skiing", "ski", "snowboard", "winter sports", "лыжи", "горные лыжи", "сноуборд", "лижі", "skifahren", "esquí", "sci", "esqui", "kayak", "スキー", "スノーボード", "스키", "스노보드"],
            symbols: ["figure.skiing.downhill", "figure.skiing.crosscountry", "figure.snowboarding", "skis.fill", "snowboard.fill", "snowflake", "mountain.2.fill"]
        ),
        IconCatalogConcept(
            terms: ["boxing", "martial arts", "karate", "wrestling", "бокс", "единоборства", "карате", "борьба", "єдиноборства", "боротьба", "boxen", "kampfsport", "ringen", "boxeo", "artes marciales", "kárate", "lucha", "boxe", "arts martiaux", "karaté", "lutte", "arti marziali", "lotta", "artes marciais", "caratê", "luta", "boks", "dövüş sanatları", "güreş", "ボクシング", "格闘技", "空手", "복싱", "무술", "태권도", "레슬링"],
            symbols: ["figure.boxing", "figure.martial.arts", "figure.kickboxing", "figure.wrestling"]
        ),
        IconCatalogConcept(
            terms: ["golf", "гольф", "golfe", "ゴルフ", "골프"],
            symbols: ["figure.golf"]
        ),
        IconCatalogConcept(
            terms: ["dance", "dancing", "танцы", "танці", "tanzen", "tanz", "baile", "danse", "danza", "ballo", "dança", "dans", "ダンス", "춤", "댄스"],
            symbols: ["figure.dance", "figure.socialdance"]
        ),
        IconCatalogConcept(
            terms: ["hiking", "camping", "outdoors", "mountains", "поход", "походы", "кемпинг", "горы", "туризм", "похід", "кемпінг", "гори", "wandern", "berge", "senderismo", "montaña", "randonnée", "montagne", "escursionismo", "campeggio", "montagna", "trilha", "acampamento", "montanha", "yürüyüş", "kamp", "dağ", "ハイキング", "キャンプ", "山", "등산", "캠핑", "산"],
            symbols: ["figure.hiking", "mountain.2.fill", "tent.fill", "binoculars.fill"]
        ),
        IconCatalogConcept(
            terms: ["fishing", "hunting", "рыбалка", "охота", "риболовля", "полювання", "angeln", "jagd", "pesca", "caza", "pêche", "chasse", "caccia", "caça", "balık tutma", "avcılık", "釣り", "狩猟", "낚시", "사냥"],
            symbols: ["figure.fishing", "fish.fill", "figure.hunting"]
        ),
        IconCatalogConcept(
            terms: ["beauty", "salon", "haircut", "barber", "hairdresser", "cosmetics", "makeup", "manicure", "красота", "салон", "стрижка", "парикмахерская", "барбершоп", "косметика", "макияж", "маникюр", "краса", "перукарня", "манікюр", "schönheit", "friseur", "haarschnitt", "kosmetik", "maniküre", "belleza", "peluquería", "barbería", "cosmética", "maquillaje", "manicura", "beauté", "coiffeur", "coupe", "barbier", "cosmétiques", "maquillage", "manucure", "bellezza", "parrucchiere", "barbiere", "cosmetici", "trucco", "beleza", "salão", "cabeleireiro", "barbearia", "cosméticos", "maquiagem", "güzellik", "kuaför", "berber", "kozmetik", "makyaj", "manikür", "美容", "美容院", "床屋", "化粧品", "ネイル", "뷰티", "미용실", "이발소", "화장품", "네일"],
            symbols: ["comb.fill", "scissors", "sparkles", "hands.and.sparkles.fill", "face.smiling.fill", "mustache.fill", "eyebrow", "wand.and.stars"]
        ),
        IconCatalogConcept(
            terms: ["hygiene", "personal care", "bath", "гигиена", "уход", "ванна", "душ", "гігієна", "догляд", "körperpflege", "bad", "higiene", "cuidado personal", "baño", "hygiène", "soins", "bain", "igiene", "cura personale", "bagno", "cuidados pessoais", "banho", "hijyen", "kişisel bakım", "banyo", "衛生", "お風呂", "ケア", "위생", "목욕", "개인 관리"],
            symbols: ["shower.fill", "bathtub.fill", "drop.fill", "comb.fill"]
        ),
        IconCatalogConcept(
            terms: ["family", "parents", "relatives", "семья", "родители", "родственники", "мама", "папа", "сім'я", "родина", "батьки", "родичі", "тато", "familie", "eltern", "verwandte", "familia", "padres", "parientes", "famille", "proches", "famiglia", "genitori", "parenti", "família", "pais", "parentes", "aile", "ebeveyn", "akraba", "anne", "baba", "家族", "両親", "親戚", "가족", "부모", "친척"],
            symbols: ["figure.2.and.child.holdinghands", "figure.and.child.holdinghands", "person.2.fill", "person.3.fill", "house.fill", "heart.fill"]
        ),
        IconCatalogConcept(
            terms: ["kids", "children", "child", "baby", "toys", "дети", "ребёнок", "малыш", "игрушки", "детский сад", "діти", "дитина", "малюк", "іграшки", "садок", "kinder", "kind", "spielzeug", "kita", "niños", "hijos", "bebé", "juguetes", "guardería", "enfants", "enfant", "bébé", "jouets", "crèche", "bambini", "figli", "neonato", "giocattoli", "asilo", "crianças", "filhos", "bebê", "brinquedos", "creche", "çocuk", "bebek", "oyuncak", "kreş", "子供", "赤ちゃん", "おもちゃ", "保育園", "아이", "아기", "장난감", "어린이집"],
            symbols: ["figure.child", "stroller.fill", "teddybear.fill", "figure.and.child.holdinghands", "balloon.fill"]
        ),
        IconCatalogConcept(
            terms: ["love", "partner", "relationship", "date", "wife", "husband", "girlfriend", "boyfriend", "любовь", "любимая", "любимый", "отношения", "свидание", "жена", "муж", "девушка", "парень", "кохання", "кохана", "коханий", "стосунки", "побачення", "дружина", "чоловік", "liebe", "beziehung", "frau", "mann", "freundin", "freund", "amor", "pareja", "cita", "esposa", "esposo", "novia", "novio", "amour", "couple", "rendez-vous", "femme", "mari", "copine", "copain", "amore", "coppia", "appuntamento", "moglie", "marito", "fidanzata", "fidanzato", "namorada", "namorado", "casal", "encontro", "marido", "aşk", "sevgili", "ilişki", "randevu", "eş", "karı", "koca", "恋人", "愛", "デート", "妻", "夫", "彼女", "彼氏", "사랑", "연인", "데이트", "아내", "남편", "여자친구", "남자친구"],
            symbols: ["heart.fill", "suit.heart.fill", "gift.fill"]
        ),
        IconCatalogConcept(
            terms: ["friends", "people", "social", "друзья", "люди", "общение", "друзі", "спілкування", "freunde", "leute", "soziales", "amigos", "gente", "amis", "gens", "amici", "persone", "sociale", "pessoas", "arkadaşlar", "insanlar", "sosyal", "友達", "人", "交流", "친구", "사람", "모임"],
            symbols: ["person.2.fill", "person.3.fill", "person.fill", "hands.clap.fill"]
        ),
        IconCatalogConcept(
            terms: ["pets", "pet", "dog", "cat", "vet", "animals", "питомцы", "животные", "собака", "кошка", "кот", "ветеринар", "зоомагазин", "тварини", "улюбленці", "кіт", "кішка", "haustier", "tiere", "hund", "katze", "tierarzt", "mascotas", "animales", "perro", "gato", "veterinario", "animaux", "animal", "chien", "chat", "vétérinaire", "animali", "cane", "gatto", "animais", "cachorro", "cão", "veterinário", "evcil hayvan", "hayvan", "köpek", "kedi", "veteriner", "ペット", "動物", "犬", "猫", "獣医", "반려동물", "동물", "강아지", "고양이", "동물병원"],
            symbols: ["pawprint.fill", "dog.fill", "cat.fill", "bird.fill", "fish.fill", "hare.fill", "tortoise.fill", "lizard.fill", "pet.carrier.fill", "service.dog.fill"]
        ),
        IconCatalogConcept(
            terms: ["education", "school", "university", "study", "courses", "tuition", "образование", "учёба", "школа", "университет", "курсы", "обучение", "освіта", "навчання", "університет", "курси", "bildung", "schule", "universität", "studium", "kurse", "educación", "escuela", "universidad", "estudios", "cursos", "éducation", "école", "université", "études", "cours", "istruzione", "scuola", "università", "studio", "corsi", "educação", "escola", "faculdade", "universidade", "eğitim", "okul", "üniversite", "kurs", "教育", "学校", "大学", "勉強", "講座", "교육", "학교", "대학", "공부", "학원"],
            symbols: ["graduationcap.fill", "book.fill", "books.vertical.fill", "backpack.fill", "pencil", "studentdesk", "text.book.closed.fill", "pencil.and.ruler.fill", "eraser.fill", "scroll.fill"]
        ),
        IconCatalogConcept(
            terms: ["books", "reading", "library", "magazine", "книги", "чтение", "библиотека", "журнал", "читання", "бібліотека", "bücher", "lesen", "bibliothek", "zeitschrift", "libros", "lectura", "biblioteca", "revista", "livres", "lecture", "bibliothèque", "libri", "lettura", "rivista", "livros", "leitura", "kitap", "okuma", "kütüphane", "dergi", "本", "読書", "図書館", "雑誌", "책", "독서", "도서관", "잡지"],
            symbols: ["book.fill", "book.closed.fill", "books.vertical.fill", "text.book.closed.fill", "magazine.fill", "newspaper.fill"]
        ),
        IconCatalogConcept(
            terms: ["work", "job", "office", "business", "работа", "офис", "бизнес", "робота", "офіс", "бізнес", "arbeit", "büro", "geschäft", "trabajo", "oficina", "negocio", "travail", "emploi", "bureau", "entreprise", "lavoro", "ufficio", "azienda", "trabalho", "emprego", "escritório", "negócio", "iş", "ofis", "şirket", "仕事", "職場", "オフィス", "ビジネス", "일", "직장", "사무실", "사업"],
            symbols: ["briefcase.fill", "building.2.fill", "desktopcomputer", "laptopcomputer", "printer.fill", "lanyardcard.fill", "megaphone.fill"]
        ),
        IconCatalogConcept(
            terms: ["salary", "income", "wage", "paycheck", "bonus", "earnings", "зарплата", "доход", "заработок", "премия", "аванс", "дохід", "заробіток", "премія", "gehalt", "lohn", "einkommen", "salario", "sueldo", "ingresos", "nómina", "salaire", "revenu", "paie", "prime", "stipendio", "reddito", "salário", "renda", "bônus", "maaş", "gelir", "prim", "給料", "収入", "給与", "ボーナス", "월급", "급여", "수입", "보너스"],
            symbols: ["banknote.fill", "dollarsign", "briefcase.fill", "chart.line.uptrend.xyaxis"]
        ),
        IconCatalogConcept(
            terms: ["money", "cash", "currency", "деньги", "наличные", "валюта", "гроші", "готівка", "geld", "bargeld", "währung", "dinero", "efectivo", "moneda", "argent", "espèces", "liquide", "devise", "soldi", "denaro", "contanti", "valuta", "dinheiro", "espécie", "moeda", "para", "nakit", "döviz", "お金", "現金", "通貨", "돈", "현금", "통화"],
            symbols: ["banknote.fill", "dollarsign", "eurosign", "rublesign", "tengesign", "sterlingsign", "yensign", "wonsign", "turkishlirasign", "hryvniasign", "brazilianrealsign", "polishzlotysign", "larisign", "manatsign", "dongsign", "bahtsign", "pesosign", "francsign", "australiandollarsign", "swedishkronasign", "norwegiankronesign", "danishkronesign", "shekelsign", "singaporedollarsign", "malaysianringgitsign", "nairasign", "centsign", "chineseyuanrenminbisign", "indianrupeesign"]
        ),
        IconCatalogConcept(
            terms: ["bank", "card", "credit card", "account", "payment", "wallet", "банк", "карта", "карточка", "счёт", "оплата", "платёж", "кошелёк", "картка", "рахунок", "платіж", "гаманець", "karte", "kreditkarte", "konto", "zahlung", "geldbörse", "banco", "tarjeta", "cuenta", "pago", "cartera", "banque", "carte", "compte", "paiement", "portefeuille", "banca", "carta", "conto", "pagamento", "portafoglio", "cartão", "conta", "carteira", "banka", "kart", "kredi kartı", "hesap", "ödeme", "cüzdan", "銀行", "カード", "口座", "支払い", "財布", "은행", "카드", "계좌", "결제", "지갑"],
            symbols: ["creditcard.fill", "building.columns.fill", "wallet.pass.fill", "wallet.bifold.fill", "creditcard.rewards.fill"]
        ),
        IconCatalogConcept(
            terms: ["savings", "investment", "deposit", "stocks", "piggy bank", "накопления", "копилка", "сбережения", "инвестиции", "вклад", "депозит", "акции", "заощадження", "скарбничка", "інвестиції", "акції", "sparen", "ersparnisse", "investition", "einlage", "aktien", "ahorro", "inversión", "depósito", "acciones", "hucha", "épargne", "investissement", "dépôt", "actions", "tirelire", "risparmi", "investimenti", "deposito", "azioni", "salvadanaio", "poupança", "investimento", "ações", "cofrinho", "birikim", "yatırım", "mevduat", "hisse", "kumbara", "貯金", "投資", "預金", "株", "저축", "투자", "예금", "주식"],
            symbols: ["chart.line.uptrend.xyaxis", "chart.bar.fill", "chart.pie.fill", "banknote.fill", "lock.fill"]
        ),
        IconCatalogConcept(
            terms: ["loan", "credit", "debt", "installment", "interest", "кредит", "долг", "долги", "займ", "рассрочка", "проценты", "борг", "позика", "розстрочка", "відсотки", "kredit", "schulden", "darlehen", "raten", "zinsen", "préstamo", "crédito", "deuda", "cuotas", "intereses", "prêt", "crédit", "dette", "mensualités", "intérêts", "prestito", "credito", "debito", "rate", "interessi", "empréstimo", "dívida", "parcelas", "juros", "kredi", "borç", "taksit", "faiz", "ローン", "借金", "分割", "利息", "대출", "빚", "할부", "이자"],
            symbols: ["creditcard.fill", "building.columns.fill", "percent", "doc.text.fill"]
        ),
        IconCatalogConcept(
            terms: ["taxes", "tax", "fees", "fines", "налоги", "налог", "пошлины", "штрафы", "податки", "податок", "мито", "штрафи", "steuern", "steuer", "gebühren", "bußgeld", "impuestos", "tasas", "multas", "impôts", "frais", "amendes", "tasse", "imposte", "multe", "impostos", "taxas", "vergi", "harç", "ceza", "税金", "手数料", "罰金", "세금", "수수료", "벌금"],
            symbols: ["doc.text.fill", "building.columns.fill", "percent", "list.clipboard.fill"]
        ),
        IconCatalogConcept(
            terms: ["crypto", "bitcoin", "крипта", "криптовалюта", "биткоин", "біткоїн", "krypto", "cripto", "kripto", "暗号資産", "ビットコイン", "암호화폐", "비트코인"],
            symbols: ["bitcoinsign"]
        ),
        IconCatalogConcept(
            terms: ["discount", "sale", "cashback", "promo", "скидка", "распродажа", "кэшбэк", "акция", "знижка", "розпродаж", "кешбек", "акція", "rabatt", "angebot", "descuento", "rebajas", "oferta", "réduction", "soldes", "sconto", "saldi", "offerta", "desconto", "promoção", "indirim", "kampanya", "nakit iade", "割引", "セール", "キャッシュバック", "할인", "세일", "캐시백"],
            symbols: ["percent", "tag.fill", "creditcard.rewards.fill"]
        ),
        IconCatalogConcept(
            terms: ["movies", "cinema", "film", "tv", "streaming", "кино", "кинотеатр", "фильмы", "сериалы", "тв", "стриминг", "кіно", "кінотеатр", "фільми", "серіали", "kino", "filme", "fernsehen", "cine", "películas", "series", "tele", "cinéma", "films", "séries", "télé", "serie", "filmes", "sinema", "dizi", "televizyon", "映画", "映画館", "ドラマ", "テレビ", "配信", "영화", "영화관", "드라마", "스트리밍"],
            symbols: ["film.fill", "film.stack.fill", "popcorn.fill", "movieclapper.fill", "tv.fill", "ticket.fill", "play.tv.fill"]
        ),
        IconCatalogConcept(
            terms: ["music", "concert", "songs", "karaoke", "музыка", "концерт", "песни", "караоке", "музика", "пісні", "musik", "konzert", "lieder", "música", "concierto", "canciones", "musique", "chansons", "karaoké", "musica", "concerto", "canzoni", "show", "canções", "karaokê", "müzik", "konser", "şarkı", "音楽", "コンサート", "カラオケ", "음악", "콘서트", "노래방"],
            symbols: ["music.note", "music.note.list", "headphones", "guitars.fill", "pianokeys", "music.mic", "hifispeaker.fill", "radio.fill", "microphone.fill", "metronome.fill"]
        ),
        IconCatalogConcept(
            terms: ["games", "gaming", "video games", "игры", "видеоигры", "гейминг", "ігри", "відеоігри", "spiele", "videospiele", "juegos", "videojuegos", "jeux", "jeux vidéo", "giochi", "videogiochi", "jogos", "videogames", "oyun", "oyunlar", "video oyunu", "ゲーム", "게임"],
            symbols: ["gamecontroller.fill", "puzzlepiece.fill", "dice.fill", "die.face.5.fill", "arcade.stick"]
        ),
        IconCatalogConcept(
            terms: ["entertainment", "leisure", "fun", "theater", "events", "tickets", "развлечения", "досуг", "театр", "мероприятия", "билеты", "розваги", "дозвілля", "заходи", "квитки", "unterhaltung", "freizeit", "entretenimiento", "ocio", "teatro", "eventos", "entradas", "loisirs", "divertissement", "théâtre", "sorties", "billets", "divertimento", "svago", "eventi", "biglietti", "entretenimento", "lazer", "ingressos", "eğlence", "tiyatro", "etkinlik", "bilet", "娯楽", "劇場", "イベント", "チケット", "여가", "오락", "공연", "행사", "티켓"],
            symbols: ["theatermasks.fill", "party.popper.fill", "ticket.fill", "balloon.fill", "star.fill", "paintpalette.fill"]
        ),
        IconCatalogConcept(
            terms: ["hobby", "art", "crafts", "photography", "хобби", "творчество", "рисование", "фото", "хобі", "творчість", "малювання", "kunst", "basteln", "fotografie", "pasatiempo", "arte", "manualidades", "fotografía", "loisirs créatifs", "dessin", "photo", "fai da te", "fotografia", "artesanato", "hobi", "sanat", "el işi", "fotoğraf", "趣味", "アート", "写真", "취미", "미술", "사진"],
            symbols: ["paintpalette.fill", "paintbrush.fill", "camera.fill", "photo.fill", "scissors"]
        ),
        IconCatalogConcept(
            terms: ["subscriptions", "subscription", "streaming", "подписки", "подписка", "підписки", "підписка", "abos", "abonnement", "suscripciones", "suscripción", "abonnements", "abbonamenti", "abbonamento", "assinaturas", "assinatura", "abonelik", "üyelik", "サブスク", "定額", "구독"],
            symbols: ["tv.fill", "music.note.list", "newspaper.fill", "icloud.fill", "calendar", "play.tv.fill", "arrow.triangle.2.circlepath"]
        ),
        IconCatalogConcept(
            terms: ["travel", "trip", "vacation", "holiday", "tourism", "путешествия", "поездка", "отпуск", "туризм", "отдых", "подорожі", "поїздка", "відпустка", "відпочинок", "reisen", "reise", "urlaub", "tourismus", "viajes", "viaje", "vacaciones", "turismo", "voyage", "voyages", "vacances", "tourisme", "viaggi", "viaggio", "vacanze", "viagem", "viagens", "férias", "seyahat", "gezi", "tatil", "turizm", "旅行", "旅", "休暇", "観光", "여행", "휴가", "관광"],
            symbols: ["airplane", "suitcase.fill", "suitcase.rolling.fill", "beach.umbrella.fill", "globe.fill", "map.fill", "tent.fill", "binoculars.fill", "mountain.2.fill"]
        ),
        IconCatalogConcept(
            terms: ["hotel", "accommodation", "hostel", "airbnb", "отель", "гостиница", "жильё", "хостел", "готель", "житло", "unterkunft", "alojamiento", "hostal", "hôtel", "hébergement", "auberge", "alloggio", "ostello", "hospedagem", "otel", "konaklama", "ホテル", "宿泊", "호텔", "숙박"],
            symbols: ["bed.double.fill", "building.fill", "house.lodge.fill", "key.fill"]
        ),
        IconCatalogConcept(
            terms: ["beach", "summer", "sea", "sun", "пляж", "лето", "море", "солнце", "літо", "сонце", "strand", "sommer", "meer", "sonne", "playa", "verano", "mar", "sol", "plage", "été", "mer", "soleil", "spiaggia", "estate", "mare", "sole", "praia", "verão", "plaj", "yaz", "deniz", "güneş", "ビーチ", "夏", "海", "太陽", "해변", "여름", "바다", "햇빛"],
            symbols: ["beach.umbrella.fill", "sun.max.fill", "water.waves", "sailboat.fill"]
        ),
        IconCatalogConcept(
            terms: ["electronics", "gadgets", "tech", "computer", "laptop", "smartphone", "электроника", "гаджеты", "техника", "компьютер", "ноутбук", "смартфон", "електроніка", "гаджети", "техніка", "комп'ютер", "elektronik", "technik", "electrónica", "tecnología", "ordenador", "portátil", "móvil", "électronique", "high-tech", "ordinateur", "portable", "elettronica", "gadget", "tecnologia", "portatile", "eletrônicos", "computador", "notebook", "celular", "teknoloji", "bilgisayar", "akıllı telefon", "家電", "ガジェット", "パソコン", "スマホ", "전자기기", "가젯", "컴퓨터", "노트북", "스마트폰"],
            symbols: ["iphone", "ipad", "laptopcomputer", "desktopcomputer", "applewatch", "headphones", "airpods", "tv.fill", "display", "keyboard.fill", "computermouse.fill", "macbook", "pc", "airtag.fill", "headset"]
        ),
        IconCatalogConcept(
            terms: ["software", "apps", "cloud", "storage", "программы", "приложения", "облако", "софт", "програми", "застосунки", "хмара", "speicher", "aplicaciones", "nube", "logiciels", "applis", "app", "aplicativos", "nuvem", "yazılım", "uygulama", "bulut", "ソフト", "アプリ", "クラウド", "소프트웨어", "앱", "클라우드"],
            symbols: ["icloud.fill", "desktopcomputer", "laptopcomputer"]
        ),
        IconCatalogConcept(
            terms: ["mail", "post", "letter", "почта", "письмо", "посылка", "пошта", "лист", "посилка", "brief", "paket", "correo", "carta", "paquete", "courrier", "poste", "lettre", "colis", "posta", "lettera", "pacco", "correio", "encomenda", "mektup", "kargo", "郵便", "手紙", "우편", "편지", "우체국"],
            symbols: ["envelope.fill", "paperplane.fill", "shippingbox.fill"]
        ),
        IconCatalogConcept(
            terms: ["gift", "gifts", "present", "подарок", "подарки", "сувенир", "подарунок", "подарунки", "сувенір", "geschenk", "geschenke", "regalo", "regalos", "cadeau", "cadeaux", "regali", "presente", "presentes", "hediye", "プレゼント", "ギフト", "贈り物", "선물"],
            symbols: ["gift.fill", "giftcard.fill", "party.popper.fill", "greetingcard.fill"]
        ),
        IconCatalogConcept(
            terms: ["holiday", "party", "celebration", "birthday", "new year", "christmas", "wedding", "праздник", "праздники", "вечеринка", "день рождения", "новый год", "свадьба", "свято", "свята", "вечірка", "день народження", "новий рік", "весілля", "feier", "geburtstag", "silvester", "weihnachten", "hochzeit", "fiesta", "celebración", "cumpleaños", "año nuevo", "navidad", "boda", "fête", "anniversaire", "nouvel an", "noël", "mariage", "festa", "compleanno", "capodanno", "natale", "matrimonio", "comemoração", "aniversário", "ano novo", "natal", "casamento", "bayram", "parti", "kutlama", "doğum günü", "yılbaşı", "düğün", "お祝い", "パーティー", "誕生日", "正月", "クリスマス", "結婚式", "축하", "파티", "생일", "새해", "크리스마스", "결혼식"],
            symbols: ["party.popper.fill", "balloon.fill", "balloon.2.fill", "birthday.cake.fill", "fireworks", "sparkles", "wineglass.fill"]
        ),
        IconCatalogConcept(
            terms: ["flowers", "garden", "plants", "цветы", "сад", "растения", "дача", "квіти", "рослини", "blumen", "garten", "pflanzen", "flores", "jardín", "plantas", "fleurs", "jardin", "plantes", "fiori", "giardino", "piante", "jardim", "çiçek", "bahçe", "bitki", "花", "庭", "植物", "꽃", "정원", "식물"],
            symbols: ["camera.macro", "leaf.fill", "tree.fill", "sprinkler.and.droplets.fill"]
        ),
        IconCatalogConcept(
            terms: ["charity", "donation", "donate", "благотворительность", "пожертвование", "донат", "благодійність", "пожертва", "spende", "spenden", "wohltätigkeit", "donación", "caridad", "donativo", "don", "dons", "charité", "donazione", "beneficenza", "doação", "caridade", "bağış", "hayır", "寄付", "募金", "기부", "후원"],
            symbols: ["heart.fill", "hands.and.sparkles.fill", "gift.fill", "hand.raised.fill"]
        ),
        IconCatalogConcept(
            terms: ["weather", "rain", "snow", "sun", "winter", "погода", "дождь", "снег", "солнце", "зима", "дощ", "сніг", "сонце", "wetter", "regen", "schnee", "sonne", "tiempo", "lluvia", "nieve", "sol", "invierno", "météo", "pluie", "neige", "soleil", "hiver", "meteo", "pioggia", "neve", "sole", "inverno", "clima", "chuva", "hava", "yağmur", "kar", "güneş", "kış", "天気", "雨", "雪", "晴れ", "冬", "날씨", "비", "눈", "해", "겨울"],
            symbols: ["sun.max.fill", "cloud.fill", "cloud.rain.fill", "cloud.snow.fill", "snowflake", "wind", "umbrella.fill", "thermometer.sun.fill", "cloud.sun.fill", "cloud.drizzle.fill", "cloud.heavyrain.fill", "cloud.fog.fill", "moon.stars.fill"]
        ),
        IconCatalogConcept(
            terms: ["nature", "eco", "green", "environment", "природа", "экология", "екологія", "natur", "umwelt", "öko", "naturaleza", "ecología", "medio ambiente", "écologie", "environnement", "natura", "ecologia", "ambiente", "natureza", "meio ambiente", "doğa", "ekoloji", "çevre", "自然", "エコ", "環境", "자연", "환경", "친환경"],
            symbols: ["leaf.fill", "tree.fill", "mountain.2.fill", "flame.fill", "drop.fill", "globe.europe.africa.fill"]
        ),
        IconCatalogConcept(
            terms: ["time", "calendar", "schedule", "deadline", "время", "календарь", "расписание", "срок", "час", "календар", "розклад", "термін", "zeit", "kalender", "termin", "frist", "tiempo", "calendario", "horario", "plazo", "temps", "calendrier", "agenda", "échéance", "tempo", "orario", "scadenza", "calendário", "prazo", "zaman", "takvim", "program", "süre", "時間", "カレンダー", "予定", "期限", "시간", "달력", "일정", "기한"],
            symbols: ["calendar", "clock.fill", "alarm.fill", "hourglass", "timer"]
        ),
        IconCatalogConcept(
            terms: ["documents", "papers", "contract", "notary", "документы", "бумаги", "договор", "нотариус", "документи", "папери", "договір", "нотаріус", "dokumente", "unterlagen", "vertrag", "notar", "documentos", "papeles", "contrato", "notario", "papiers", "contrat", "notaire", "documenti", "carte", "contratto", "notaio", "papéis", "cartório", "belge", "evrak", "sözleşme", "noter", "書類", "契約", "公証", "서류", "문서", "계약", "공증"],
            symbols: ["doc.text.fill", "folder.fill", "paperclip", "signature", "list.clipboard.fill", "archivebox.fill", "tray.fill", "clipboard.fill", "text.document.fill", "scroll.fill"]
        ),
        IconCatalogConcept(
            terms: ["government", "legal", "lawyer", "court", "госуслуги", "юрист", "адвокат", "суд", "государство", "держпослуги", "behörde", "anwalt", "gericht", "recht", "gobierno", "abogado", "tribunal", "trámites", "administration", "avocat", "justice", "pubblica amministrazione", "avvocato", "tribunale", "governo", "advogado", "devlet", "avukat", "mahkeme", "hukuk", "行政", "弁護士", "裁判所", "관공서", "변호사", "법원"],
            symbols: ["building.columns.fill", "doc.text.fill", "checkmark.seal.fill"]
        ),
        IconCatalogConcept(
            terms: ["security", "lock", "keys", "password", "безопасность", "замок", "ключи", "пароль", "безпека", "ключі", "sicherheit", "schloss", "schlüssel", "passwort", "seguridad", "candado", "llaves", "contraseña", "sécurité", "serrure", "clés", "mot de passe", "sicurezza", "lucchetto", "chiavi", "segurança", "cadeado", "chaves", "senha", "güvenlik", "kilit", "anahtar", "şifre", "セキュリティ", "鍵", "パスワード", "보안", "자물쇠", "열쇠", "비밀번호"],
            symbols: ["lock.fill", "key.fill", "lock.shield.fill"]
        ),
        IconCatalogConcept(
            terms: ["transfer", "transfers", "send money", "money transfer", "перевод", "переводы", "перевод денег", "переказ", "перекази", "переказ грошей", "überweisung", "überweisungen", "geld senden", "transferencia", "transferencias", "envío de dinero", "virement", "virements", "envoi d'argent", "bonifico", "bonifici", "trasferimento", "transferência", "transferências", "pix", "havale", "eft", "para transferi", "振込", "送金", "이체", "송금"],
            symbols: ["arrow.left.arrow.right", "banknote.fill", "creditcard.fill", "paperplane.fill", "building.columns.fill"]
        ),
        IconCatalogConcept(
            terms: ["recurring", "regular payment", "monthly", "регулярные", "регулярный платёж", "ежемесячно", "регулярні", "регулярний платіж", "щомісяця", "wiederkehrend", "dauerauftrag", "monatlich", "recurrente", "pago periódico", "mensual", "récurrent", "prélèvement", "mensuel", "ricorrente", "pagamento periodico", "mensile", "recorrente", "pagamento recorrente", "mensal", "düzenli", "düzenli ödeme", "aylık", "定期", "毎月", "정기", "매월", "자동이체"],
            symbols: ["arrow.triangle.2.circlepath", "calendar"]
        ),
        IconCatalogConcept(
            terms: ["translation", "translator", "languages", "переводчик", "языки", "иностранный язык", "перекладач", "мови", "іноземна мова", "übersetzung", "übersetzer", "sprachen", "traducción", "traductor", "idiomas", "traduction", "traducteur", "langues", "traduzione", "traduttore", "lingue", "tradução", "tradutor", "çeviri", "tercüman", "dil", "翻訳", "語学", "번역", "통역", "어학"],
            symbols: ["translate"]
        ),
        IconCatalogConcept(
            terms: ["rugby", "american football", "cricket", "регби", "американский футбол", "крикет", "регбі", "американський футбол", "fútbol americano", "críquet", "football américain", "football americano", "rúgbi", "futebol americano", "críquete", "ragbi", "amerikan futbolu", "kriket", "ラグビー", "アメフト", "クリケット", "럭비", "미식축구", "크리켓"],
            symbols: ["rugbyball.fill", "cricket.ball.fill", "figure.rugby", "figure.american.football"]
        ),
        IconCatalogConcept(
            terms: ["other", "misc", "general", "favorite", "другое", "прочее", "разное", "избранное", "інше", "різне", "обране", "sonstiges", "andere", "allgemein", "favorit", "otros", "varios", "favorito", "autre", "divers", "général", "favori", "altro", "varie", "generale", "preferito", "outros", "diversos", "geral", "diğer", "çeşitli", "genel", "その他", "雑費", "お気に入り", "기타", "잡비", "즐겨찾기"],
            symbols: ["star.fill", "heart.fill", "sparkles", "bookmark.fill", "flag.fill", "tag.fill"]
        ),
        IconCatalogConcept(
            terms: ["dollar", "доллар", "долар", "dólar", "dollaro", "dolar", "ドル", "달러"],
            symbols: ["dollarsign", "australiandollarsign", "singaporedollarsign"]
        ),
        IconCatalogConcept(
            terms: ["euro", "евро", "євро", "ユーロ", "유로"],
            symbols: ["eurosign"]
        ),
        IconCatalogConcept(
            terms: ["ruble", "rouble", "рубль", "rubel", "rublo", "ルーブル", "루블"],
            symbols: ["rublesign"]
        ),
        IconCatalogConcept(
            terms: ["tenge", "тенге", "теньге", "テンゲ", "텡게"],
            symbols: ["tengesign"]
        ),
        IconCatalogConcept(
            terms: ["hryvnia", "гривна", "гривня", "hrywnja", "grivna", "grivnia", "grívnia", "フリヴニャ", "흐리우냐"],
            symbols: ["hryvniasign"]
        ),
        IconCatalogConcept(
            terms: ["lira", "turkish lira", "лира", "ліра", "livre turque", "lira turca", "türk lirası", "リラ", "리라"],
            symbols: ["turkishlirasign"]
        ),
        IconCatalogConcept(
            terms: ["pound", "sterling", "фунт", "pfund", "libra", "livre sterling", "sterlina", "sterlin", "ポンド", "파운드"],
            symbols: ["sterlingsign"]
        ),
        IconCatalogConcept(
            terms: ["yen", "иена", "йена", "єна", "iene", "円", "엔"],
            symbols: ["yensign"]
        ),
        IconCatalogConcept(
            terms: ["won", "вона", "ウォン", "원"],
            symbols: ["wonsign"]
        ),
        IconCatalogConcept(
            terms: ["rupee", "рупия", "рупія", "rupie", "rupia", "roupie", "rupi", "ルピー", "루피"],
            symbols: ["indianrupeesign"]
        ),
        IconCatalogConcept(
            terms: ["yuan", "renminbi", "юань", "人民元", "元", "위안"],
            symbols: ["chineseyuanrenminbisign"]
        ),
        IconCatalogConcept(
            terms: ["real", "реал", "réal", "レアル", "헤알"],
            symbols: ["brazilianrealsign"]
        ),
        IconCatalogConcept(
            terms: ["zloty", "злотый", "злотий", "esloti", "zlóti", "zloti", "ズウォティ", "즐로티"],
            symbols: ["polishzlotysign"]
        ),
        IconCatalogConcept(
            terms: ["lari", "лари", "ларі", "ラリ", "라리"],
            symbols: ["larisign"]
        ),
        IconCatalogConcept(
            terms: ["manat", "манат", "マナト", "마나트"],
            symbols: ["manatsign"]
        ),
        IconCatalogConcept(
            terms: ["franc", "франк", "franken", "franco", "frank", "フラン", "프랑"],
            symbols: ["francsign"]
        ),
        IconCatalogConcept(
            terms: ["shekel", "шекель", "schekel", "séquel", "şekel", "シェケル", "셰켈"],
            symbols: ["shekelsign"]
        ),
        IconCatalogConcept(
            terms: ["dong", "донг", "ドン", "동"],
            symbols: ["dongsign"]
        ),
        IconCatalogConcept(
            terms: ["baht", "бат", "バーツ", "바트"],
            symbols: ["bahtsign"]
        ),
        IconCatalogConcept(
            terms: ["peso", "песо", "ペソ", "페소"],
            symbols: ["pesosign"]
        ),
        IconCatalogConcept(
            terms: ["krona", "krone", "крона", "corona", "couronne", "coroa", "kron", "クローナ", "クローネ", "크로나", "크로네"],
            symbols: ["swedishkronasign", "norwegiankronesign", "danishkronesign"]
        ),
    ]

    /// Apple's English search keywords (SF Symbols metadata), per catalog symbol.
    static let appleKeywords: [IconCatalogKeywords] = [
        IconCatalogKeywords(symbol: "fork.knife", words: ["drink", "food"]),
        IconCatalogKeywords(symbol: "takeoutbag.and.cup.and.straw.fill", words: ["drink"]),
        IconCatalogKeywords(symbol: "cup.and.saucer.fill", words: ["coffee", "drink", "tea"]),
        IconCatalogKeywords(symbol: "cup.and.heat.waves.fill", words: ["coffee", "drink", "steam", "tea"]),
        IconCatalogKeywords(symbol: "mug.fill", words: ["coffee", "drink", "tea"]),
        IconCatalogKeywords(symbol: "wineglass.fill", words: ["drink"]),
        IconCatalogKeywords(symbol: "waterbottle.fill", words: ["drink"]),
        IconCatalogKeywords(symbol: "birthday.cake.fill", words: ["baking", "food"]),
        IconCatalogKeywords(symbol: "carrot.fill", words: ["food"]),
        IconCatalogKeywords(symbol: "fish.fill", words: ["animals"]),
        IconCatalogKeywords(symbol: "frying.pan.fill", words: ["cooking"]),
        IconCatalogKeywords(symbol: "popcorn.fill", words: ["movie"]),
        IconCatalogKeywords(symbol: "spoon.serving", words: ["drink", "food"]),
        IconCatalogKeywords(symbol: "bicycle", words: ["bike"]),
        IconCatalogKeywords(symbol: "signpost.right.fill", words: ["campground", "camping", "trail"]),
        IconCatalogKeywords(symbol: "figure.walk", words: ["human", "indoor walk", "outdoor walk", "person", "sports", "walking"]),
        IconCatalogKeywords(symbol: "helmet.fill", words: ["bike"]),
        IconCatalogKeywords(symbol: "hanger", words: ["clothing"]),
        IconCatalogKeywords(symbol: "backpack.fill", words: ["camping"]),
        IconCatalogKeywords(symbol: "hat.cap.fill", words: ["baseball"]),
        IconCatalogKeywords(symbol: "house.fill", words: ["home", "house"]),
        IconCatalogKeywords(symbol: "house.lodge.fill", words: ["campground", "camping"]),
        IconCatalogKeywords(symbol: "key.fill", words: ["password", "security"]),
        IconCatalogKeywords(symbol: "sofa.fill", words: ["couch"]),
        IconCatalogKeywords(symbol: "bed.double.fill", words: ["medical", "sleep"]),
        IconCatalogKeywords(symbol: "lamp.desk.fill", words: ["light"]),
        IconCatalogKeywords(symbol: "lamp.floor.fill", words: ["light"]),
        IconCatalogKeywords(symbol: "lamp.table.fill", words: ["light"]),
        IconCatalogKeywords(symbol: "lamp.ceiling.fill", words: ["light"]),
        IconCatalogKeywords(symbol: "bolt.fill", words: ["camera", "energy", "power"]),
        IconCatalogKeywords(symbol: "drop.fill", words: ["blood", "oil", "water"]),
        IconCatalogKeywords(symbol: "flame.fill", words: ["fire"]),
        IconCatalogKeywords(symbol: "spigot.fill", words: ["faucet"]),
        IconCatalogKeywords(symbol: "toilet.fill", words: ["campground", "camping"]),
        IconCatalogKeywords(symbol: "trash.fill", words: ["mail", "trash"]),
        IconCatalogKeywords(symbol: "sprinkler.and.droplets.fill", words: ["water"]),
        IconCatalogKeywords(symbol: "chandelier.fill", words: ["light"]),
        IconCatalogKeywords(symbol: "poweroutlet.type.f.fill", words: ["europe", "russia"]),
        IconCatalogKeywords(symbol: "cross.case.fill", words: ["first aid", "first aid kit", "firstaid", "kit", "medical"]),
        IconCatalogKeywords(symbol: "cross.fill", words: ["medical"]),
        IconCatalogKeywords(symbol: "pills.fill", words: ["medical"]),
        IconCatalogKeywords(symbol: "syringe.fill", words: ["covid", "medical", "virus"]),
        IconCatalogKeywords(symbol: "bandage.fill", words: ["medical"]),
        IconCatalogKeywords(symbol: "waveform.path.ecg", words: ["medical"]),
        IconCatalogKeywords(symbol: "heart.text.clipboard.fill", words: ["notes"]),
        IconCatalogKeywords(symbol: "cross.vial.fill", words: ["medical"]),
        IconCatalogKeywords(symbol: "medical.thermometer.fill", words: ["covid", "medical", "temperature"]),
        IconCatalogKeywords(symbol: "ivfluid.bag.fill", words: ["medical"]),
        IconCatalogKeywords(symbol: "eye.fill", words: ["quick look", "quicklook", "show"]),
        IconCatalogKeywords(symbol: "allergens.fill", words: ["covid", "exposure", "medical", "virus"]),
        IconCatalogKeywords(symbol: "facemask.fill", words: ["medical"]),
        IconCatalogKeywords(symbol: "microbe.fill", words: ["covid", "exposure", "medical", "virus"]),
        IconCatalogKeywords(symbol: "staroflife.fill", words: ["medical"]),
        IconCatalogKeywords(symbol: "testtube.2", words: ["medical"]),
        IconCatalogKeywords(symbol: "flask.fill", words: ["medical"]),
        IconCatalogKeywords(symbol: "figure.mind.and.body", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "pill.fill", words: ["medical"]),
        IconCatalogKeywords(symbol: "bolt.heart.fill", words: ["medical"]),
        IconCatalogKeywords(symbol: "thermometer.medium", words: ["weather"]),
        IconCatalogKeywords(symbol: "scissors", words: ["cut"]),
        IconCatalogKeywords(symbol: "sparkles", words: ["weather"]),
        IconCatalogKeywords(symbol: "face.smiling.fill", words: ["friendly", "smile"]),
        IconCatalogKeywords(symbol: "figure.2.and.child.holdinghands", words: ["adult", "child", "family", "human", "kid", "parent", "person"]),
        IconCatalogKeywords(symbol: "figure.and.child.holdinghands", words: ["adult", "child", "family", "human", "kid", "parent", "person"]),
        IconCatalogKeywords(symbol: "figure.child", words: ["human", "person"]),
        IconCatalogKeywords(symbol: "teddybear.fill", words: ["animals", "pet friendly"]),
        IconCatalogKeywords(symbol: "person.fill", words: ["people", "user"]),
        IconCatalogKeywords(symbol: "person.2.fill", words: ["people", "shared"]),
        IconCatalogKeywords(symbol: "person.3.fill", words: ["group", "people", "shared"]),
        IconCatalogKeywords(symbol: "figure.2.arms.open", words: ["human", "person"]),
        IconCatalogKeywords(symbol: "hand.thumbsup.fill", words: ["like"]),
        IconCatalogKeywords(symbol: "heart.fill", words: ["love", "medical"]),
        IconCatalogKeywords(symbol: "figure.2", words: ["human", "person"]),
        IconCatalogKeywords(symbol: "pawprint.fill", words: ["animals", "pet friendly"]),
        IconCatalogKeywords(symbol: "dog.fill", words: ["animals"]),
        IconCatalogKeywords(symbol: "cat.fill", words: ["animals"]),
        IconCatalogKeywords(symbol: "bird.fill", words: ["animals"]),
        IconCatalogKeywords(symbol: "hare.fill", words: ["animals", "fast", "rabbit"]),
        IconCatalogKeywords(symbol: "tortoise.fill", words: ["animals", "slow", "turtle"]),
        IconCatalogKeywords(symbol: "lizard.fill", words: ["animals", "reptile"]),
        IconCatalogKeywords(symbol: "ant.fill", words: ["animals", "bug", "radar"]),
        IconCatalogKeywords(symbol: "ladybug.fill", words: ["animals", "bug"]),
        IconCatalogKeywords(symbol: "pet.carrier.fill", words: ["luggage"]),
        IconCatalogKeywords(symbol: "service.dog.fill", words: ["animals"]),
        IconCatalogKeywords(symbol: "graduationcap.fill", words: ["college", "education", "hat", "school", "student"]),
        IconCatalogKeywords(symbol: "book.fill", words: ["bookmark"]),
        IconCatalogKeywords(symbol: "text.book.closed.fill", words: ["dictionary"]),
        IconCatalogKeywords(symbol: "pencil", words: ["edit", "rename", "write", "writing"]),
        IconCatalogKeywords(symbol: "highlighter", words: ["write", "writing"]),
        IconCatalogKeywords(symbol: "folder.fill", words: ["move"]),
        IconCatalogKeywords(symbol: "tray.fill", words: ["inbox", "mail"]),
        IconCatalogKeywords(symbol: "archivebox.fill", words: ["archive", "mail"]),
        IconCatalogKeywords(symbol: "paperclip", words: ["attach", "attachments", "mail"]),
        IconCatalogKeywords(symbol: "list.clipboard.fill", words: ["notes"]),
        IconCatalogKeywords(symbol: "pencil.and.list.clipboard", words: ["notes"]),
        IconCatalogKeywords(symbol: "globe.desk.fill", words: ["geography"]),
        IconCatalogKeywords(symbol: "atom", words: ["science"]),
        IconCatalogKeywords(symbol: "pencil.tip", words: ["write", "writing"]),
        IconCatalogKeywords(symbol: "dollarsign", words: ["currencies", "currency"]),
        IconCatalogKeywords(symbol: "eurosign", words: ["currencies", "currency"]),
        IconCatalogKeywords(symbol: "rublesign", words: ["currencies", "currency"]),
        IconCatalogKeywords(symbol: "tengesign", words: ["currencies", "currency"]),
        IconCatalogKeywords(symbol: "sterlingsign", words: ["currencies", "currency"]),
        IconCatalogKeywords(symbol: "yensign", words: ["currencies", "currency"]),
        IconCatalogKeywords(symbol: "chineseyuanrenminbisign", words: ["currencies", "currency"]),
        IconCatalogKeywords(symbol: "turkishlirasign", words: ["currencies", "currency"]),
        IconCatalogKeywords(symbol: "wonsign", words: ["currencies", "currency"]),
        IconCatalogKeywords(symbol: "indianrupeesign", words: ["currencies", "currency"]),
        IconCatalogKeywords(symbol: "bitcoinsign", words: ["currencies", "currency"]),
        IconCatalogKeywords(symbol: "percent", words: ["%"]),
        IconCatalogKeywords(symbol: "lock.shield.fill", words: ["padlock", "password", "security"]),
        IconCatalogKeywords(symbol: "lock.fill", words: ["lock", "padlock", "password", "security"]),
        IconCatalogKeywords(symbol: "hryvniasign", words: ["currencies", "currency"]),
        IconCatalogKeywords(symbol: "brazilianrealsign", words: ["currencies", "currency"]),
        IconCatalogKeywords(symbol: "polishzlotysign", words: ["currencies", "currency"]),
        IconCatalogKeywords(symbol: "larisign", words: ["currencies", "currency"]),
        IconCatalogKeywords(symbol: "manatsign", words: ["currencies", "currency"]),
        IconCatalogKeywords(symbol: "dongsign", words: ["currencies", "currency"]),
        IconCatalogKeywords(symbol: "bahtsign", words: ["currencies", "currency"]),
        IconCatalogKeywords(symbol: "pesosign", words: ["currencies", "currency"]),
        IconCatalogKeywords(symbol: "francsign", words: ["currencies", "currency"]),
        IconCatalogKeywords(symbol: "australiandollarsign", words: ["currencies", "currency"]),
        IconCatalogKeywords(symbol: "swedishkronasign", words: ["currencies", "currency"]),
        IconCatalogKeywords(symbol: "norwegiankronesign", words: ["currencies", "currency"]),
        IconCatalogKeywords(symbol: "danishkronesign", words: ["currencies", "currency"]),
        IconCatalogKeywords(symbol: "shekelsign", words: ["currencies", "currency"]),
        IconCatalogKeywords(symbol: "singaporedollarsign", words: ["currencies", "currency"]),
        IconCatalogKeywords(symbol: "malaysianringgitsign", words: ["currencies", "currency"]),
        IconCatalogKeywords(symbol: "nairasign", words: ["currencies", "currency"]),
        IconCatalogKeywords(symbol: "centsign", words: ["currencies", "currency"]),
        IconCatalogKeywords(symbol: "music.note", words: ["media"]),
        IconCatalogKeywords(symbol: "music.note.list", words: ["media"]),
        IconCatalogKeywords(symbol: "party.popper.fill", words: ["party"]),
        IconCatalogKeywords(symbol: "photo.fill", words: ["environment", "image", "mountain", "photograph", "picture", "place", "sun"]),
        IconCatalogKeywords(symbol: "figure.dance", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.socialdance", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "microphone.fill", words: ["dictate", "dictation"]),
        IconCatalogKeywords(symbol: "photo.artframe", words: ["environment", "image", "mountain", "photograph", "picture", "place", "sun"]),
        IconCatalogKeywords(symbol: "arcade.stick", words: ["neutral", "tilt"]),
        IconCatalogKeywords(symbol: "suitcase.fill", words: ["luggage"]),
        IconCatalogKeywords(symbol: "suitcase.rolling.fill", words: ["luggage"]),
        IconCatalogKeywords(symbol: "suitcase.cart.fill", words: ["luggage"]),
        IconCatalogKeywords(symbol: "tent.fill", words: ["campground", "camping"]),
        IconCatalogKeywords(symbol: "tent.2.fill", words: ["campground", "camping"]),
        IconCatalogKeywords(symbol: "mountain.2.fill", words: ["campground", "camping", "trail"]),
        IconCatalogKeywords(symbol: "globe.fill", words: ["earth", "language"]),
        IconCatalogKeywords(symbol: "globe.europe.africa.fill", words: ["earth"]),
        IconCatalogKeywords(symbol: "globe.americas.fill", words: ["earth"]),
        IconCatalogKeywords(symbol: "globe.asia.australia.fill", words: ["earth"]),
        IconCatalogKeywords(symbol: "figure.hiking", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.walk.suitcase.rolling", words: ["gate", "human", "person", "walking"]),
        IconCatalogKeywords(symbol: "globe.central.south.asia.fill", words: ["earth"]),
        IconCatalogKeywords(symbol: "sun.horizon.fill", words: ["weather"]),
        IconCatalogKeywords(symbol: "dumbbell.fill", words: ["sports"]),
        IconCatalogKeywords(symbol: "sportscourt.fill", words: ["sports"]),
        IconCatalogKeywords(symbol: "soccerball", words: ["football", "sports"]),
        IconCatalogKeywords(symbol: "basketball.fill", words: ["sports"]),
        IconCatalogKeywords(symbol: "tennis.racket", words: ["sports"]),
        IconCatalogKeywords(symbol: "tennisball.fill", words: ["sports"]),
        IconCatalogKeywords(symbol: "baseball.fill", words: ["sports"]),
        IconCatalogKeywords(symbol: "volleyball.fill", words: ["sports"]),
        IconCatalogKeywords(symbol: "hockey.puck.fill", words: ["sports"]),
        IconCatalogKeywords(symbol: "skateboard.fill", words: ["sports"]),
        IconCatalogKeywords(symbol: "skis.fill", words: ["sports"]),
        IconCatalogKeywords(symbol: "snowboard.fill", words: ["sports"]),
        IconCatalogKeywords(symbol: "surfboard.fill", words: ["sports"]),
        IconCatalogKeywords(symbol: "oar.2.crossed", words: ["paddling", "sports"]),
        IconCatalogKeywords(symbol: "figure.run", words: ["human", "outdoor run", "person", "running", "sports"]),
        IconCatalogKeywords(symbol: "figure.run.treadmill", words: ["human", "indoor run", "person", "running", "sports"]),
        IconCatalogKeywords(symbol: "figure.strengthtraining.traditional", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.strengthtraining.functional", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.cross.training", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.core.training", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.highintensity.intervaltraining", words: ["hiit", "human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.mixed.cardio", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.elliptical", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.stair.stepper", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.jumprope", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.yoga", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.pilates", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.flexibility", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.cooldown", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.pool.swim", words: ["human", "person", "sports", "water"]),
        IconCatalogKeywords(symbol: "figure.open.water.swim", words: ["human", "person", "sports", "water"]),
        IconCatalogKeywords(symbol: "figure.water.fitness", words: ["human", "person", "sports", "water"]),
        IconCatalogKeywords(symbol: "figure.outdoor.cycle", words: ["bicycle", "human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.indoor.cycle", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.basketball", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.volleyball", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.tennis", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.table.tennis", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.badminton", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.hockey", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.ice.hockey", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.ice.skating", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.skiing.downhill", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.skiing.crosscountry", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.snowboarding", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.skateboarding", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.surfing", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.sailing", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.climbing", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.boxing", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.kickboxing", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.martial.arts", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.wrestling", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.fencing", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.gymnastics", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.golf", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.bowling", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.archery", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.equestrian.sports", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.track.and.field", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.fishing", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.hunting", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.american.football", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.baseball", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.handball", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.rugby", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.taichi", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "rugbyball.fill", words: ["sports"]),
        IconCatalogKeywords(symbol: "cricket.ball.fill", words: ["sports"]),
        IconCatalogKeywords(symbol: "duffle.bag.fill", words: ["sports"]),
        IconCatalogKeywords(symbol: "flag.pattern.checkered", words: ["campground", "camping"]),
        IconCatalogKeywords(symbol: "figure.squash", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.indoor.rowing", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.barre", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.step.training", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.walk.treadmill", words: ["human", "indoor walk", "person", "sports"]),
        IconCatalogKeywords(symbol: "figure.curling", words: ["human", "person", "sports"]),
        IconCatalogKeywords(symbol: "desktopcomputer", words: ["imac", "mac"]),
        IconCatalogKeywords(symbol: "airpods", words: ["audio", "sound", "speaker"]),
        IconCatalogKeywords(symbol: "earbuds", words: ["audio", "sound", "speaker"]),
        IconCatalogKeywords(symbol: "headphones", words: ["audio", "sound", "speaker"]),
        IconCatalogKeywords(symbol: "homepod.fill", words: ["audio", "sound", "speaker"]),
        IconCatalogKeywords(symbol: "macmini.fill", words: ["mac mini"]),
        IconCatalogKeywords(symbol: "printer.fill", words: ["mail", "print"]),
        IconCatalogKeywords(symbol: "cpu.fill", words: ["chip", "cpu", "gpu"]),
        IconCatalogKeywords(symbol: "memorychip.fill", words: ["chip", "cpu", "gpu"]),
        IconCatalogKeywords(symbol: "envelope.fill", words: ["address", "letter", "mail"]),
        IconCatalogKeywords(symbol: "antenna.radiowaves.left.and.right", words: ["cellular", "lte"]),
        IconCatalogKeywords(symbol: "hifispeaker.fill", words: ["audio", "sound", "speaker"]),
        IconCatalogKeywords(symbol: "airtag.fill", words: ["findable", "location"]),
        IconCatalogKeywords(symbol: "headset", words: ["concierge", "road assistance"]),
        IconCatalogKeywords(symbol: "video.fill", words: ["facetime"]),
        IconCatalogKeywords(symbol: "envelope.open.fill", words: ["address", "letter", "mail"]),
        IconCatalogKeywords(symbol: "waveform", words: ["audio", "high", "record", "speech", "voice memo"]),
        IconCatalogKeywords(symbol: "paperplane.fill", words: ["send"]),
        IconCatalogKeywords(symbol: "scalemass.fill", words: ["weight"]),
        IconCatalogKeywords(symbol: "gearshape.fill", words: ["general", "settings"]),
        IconCatalogKeywords(symbol: "gearshape.2.fill", words: ["advanced"]),
        IconCatalogKeywords(symbol: "bell.fill", words: ["mail", "notify"]),
        IconCatalogKeywords(symbol: "exclamationmark.triangle.fill", words: ["warning"]),
        IconCatalogKeywords(symbol: "hand.raised.fill", words: ["block", "privacy"]),
        IconCatalogKeywords(symbol: "magnifyingglass", words: ["search"]),
        IconCatalogKeywords(symbol: "gift.fill", words: ["birthday"]),
        IconCatalogKeywords(symbol: "balloon.fill", words: ["party"]),
        IconCatalogKeywords(symbol: "balloon.2.fill", words: ["party"]),
        IconCatalogKeywords(symbol: "fireworks", words: ["party"]),
        IconCatalogKeywords(symbol: "star.fill", words: ["favorite", "mail", "vip"]),
        IconCatalogKeywords(symbol: "tree.fill", words: ["campground", "camping"]),
        IconCatalogKeywords(symbol: "camera.macro", words: ["macro"]),
        IconCatalogKeywords(symbol: "sun.max.fill", words: ["weather"]),
        IconCatalogKeywords(symbol: "moon.fill", words: ["dnd", "do not disturb", "weather"]),
        IconCatalogKeywords(symbol: "cloud.fill", words: ["weather"]),
        IconCatalogKeywords(symbol: "cloud.rain.fill", words: ["weather"]),
        IconCatalogKeywords(symbol: "cloud.snow.fill", words: ["weather"]),
        IconCatalogKeywords(symbol: "cloud.bolt.fill", words: ["weather"]),
        IconCatalogKeywords(symbol: "snowflake", words: ["weather"]),
        IconCatalogKeywords(symbol: "wind", words: ["weather"]),
        IconCatalogKeywords(symbol: "rainbow", words: ["weather"]),
        IconCatalogKeywords(symbol: "sunrise.fill", words: ["arrow", "weather"]),
        IconCatalogKeywords(symbol: "sunset.fill", words: ["arrow", "weather"]),
        IconCatalogKeywords(symbol: "thermometer.sun.fill", words: ["weather"]),
        IconCatalogKeywords(symbol: "humidity.fill", words: ["drop", "weather"]),
        IconCatalogKeywords(symbol: "tornado", words: ["weather"]),
        IconCatalogKeywords(symbol: "water.waves", words: ["dive", "ocean", "sea", "sports", "surface", "swim", "water", "wave"]),
        IconCatalogKeywords(symbol: "cloud.sun.fill", words: ["weather"]),
        IconCatalogKeywords(symbol: "cloud.moon.fill", words: ["weather"]),
        IconCatalogKeywords(symbol: "moon.stars.fill", words: ["weather"]),
        IconCatalogKeywords(symbol: "cloud.drizzle.fill", words: ["weather"]),
        IconCatalogKeywords(symbol: "cloud.fog.fill", words: ["weather"]),
        IconCatalogKeywords(symbol: "cloud.heavyrain.fill", words: ["weather"]),
        IconCatalogKeywords(symbol: "sun.haze.fill", words: ["weather"]),
        IconCatalogKeywords(symbol: "hurricane", words: ["weather"]),
        IconCatalogKeywords(symbol: "tropicalstorm", words: ["weather"]),
        IconCatalogKeywords(symbol: "smoke.fill", words: ["weather"]),
        IconCatalogKeywords(symbol: "bookmark.fill", words: ["bookmark"]),
        IconCatalogKeywords(symbol: "flag.fill", words: ["mail"]),
        IconCatalogKeywords(symbol: "pin.fill", words: ["pin"]),
        IconCatalogKeywords(symbol: "timer", words: ["timer"]),
        IconCatalogKeywords(symbol: "alarm.fill", words: ["alarm"]),
        IconCatalogKeywords(symbol: "clock.fill", words: ["history", "recent"]),
        IconCatalogKeywords(symbol: "calendar", words: ["calendar", "date"]),
        IconCatalogKeywords(symbol: "at", words: ["@"]),
        IconCatalogKeywords(symbol: "questionmark", words: ["?"]),
        IconCatalogKeywords(symbol: "exclamationmark", words: ["!", "warning"]),
    ]
}
