//
//  IconCatalogTests.swift
//  TenraTests
//
//  The icon picker's catalog (generated by scripts/generate_icon_catalog.py) and
//  its search across the app's 11 languages.
//

import Testing
import UIKit
@testable import Tenra

struct IconCatalogTests {

    @Test func everySymbolRendersAndAppearsOnce() {
        #expect(IconCatalog.allSymbols.count >= 500)
        #expect(Set(IconCatalog.allSymbols).count == IconCatalog.allSymbols.count)
        let missing = (IconCatalog.allSymbols + IconCatalog.frequentlyUsed).filter { UIImage(systemName: $0) == nil }
        #expect(missing.isEmpty, "not an SF Symbol: \(missing)")
    }

    @Test func conceptsAndKeywordsPointIntoTheCatalog() {
        let catalog = Set(IconCatalog.allSymbols)
        for concept in IconCatalog.concepts {
            #expect(!concept.terms.isEmpty)
            #expect(concept.symbols.allSatisfy(catalog.contains), "\(concept.terms.first ?? "")")
        }
        #expect(IconCatalog.appleKeywords.allSatisfy { catalog.contains($0.symbol) })
    }

    @Test func groupTitlesAreLocalized() {
        for group in IconCatalog.groups {
            #expect(String(localized: String.LocalizationValue(group.titleKey)) != group.titleKey, "\(group.titleKey)")
        }
    }

    @Test(arguments: [
        ("кофе", "cup.and.saucer.fill"),       // ru
        ("kahve", "cup.and.saucer.fill"),      // tr
        ("コーヒー", "cup.and.saucer.fill"),    // ja
        ("машины", "car.fill"),                // an inflected form
        ("такс", "car.fill"),                  // typing in progress
        ("любимая", "heart.fill"),
        ("Überweisung", "arrow.left.arrow.right"),
        ("pet", "pawprint.fill"),
        ("dog", "dog.fill"),                   // Apple's English keywords
        ("гривна", "hryvniasign"),
        ("кав'ярня", "cup.and.saucer.fill")    // apostrophes do not matter
    ])
    func searchFindsAcrossLanguages(query: String, symbol: String) {
        #expect(IconCatalog.search(query).contains(symbol), "\(query) → \(IconCatalog.search(query).prefix(8))")
    }

    @Test func exactConceptMatchesComeFirst() {
        let results = IconCatalog.search("кофе")
        #expect(results.first.map { ["cup.and.saucer.fill", "mug.fill", "cup.and.heat.waves.fill"].contains($0) } == true)
    }

    @Test func groupTitleFindsTheWholeGroup() {
        let titles = IconCatalog.groups.map { $0.titleKey == "iconPicker.group.pets" ? "Питомцы" : "—" }
        let pets = IconCatalog.groups.first { $0.titleKey == "iconPicker.group.pets" }!.symbols
        #expect(Set(pets).isSubset(of: Set(IconCatalog.search("питом", groupTitles: titles))))
    }

    @Test func emptyAndUnknownQueries() {
        #expect(IconCatalog.search("   ").isEmpty)
        #expect(IconCatalog.search("zzqxw").isEmpty)
    }
}
